### ISSUE TITLE
Layout width in percentages

### ISSUE THREAD

**Issue by kwarkjes** [histoire-dev/histoire#112]
### Describe the bug

When the width is given in percentages the _variants_ don't fit as you would expect.
In the example below the expected width for each variant is supposed to be 25%. But it does not fit because of the grid gap of 1rem (It does fit if you disable the gap)

```vue
<template>
  <Story
    title="Grid in percentages"
    :layout="{
      type: 'grid',
      width: '25%',
    }"
  >
...
```

This generates the following CSS:

```css
  grid-template-columns: repeat(auto-fill, 25%);
```
and that seems not to work for some reason check this [codepen that verifies that](https://codepen.io/kwarkjes/pen/VwQBwVM?editors=0100)

![image](https://user-images.githubusercontent.com/1968892/172002851-a282a00a-cd28-41b1-8e9a-c2e81dc46193.png)

### Reproduction

As you can see here the layout should have been like a 50-50%

https://stackblitz.com/edit/histoire-vue3-starter-h95gmw?file=src%2FBaseButton.story.vue

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 61.09 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Columns in percentage have to take into account the gap which is 16px:
https://stackoverflow.com/a/45092180

It works in your repro with:

```
<Story :layout="{ type: 'grid', width: 'calc(50% - 8px)' }">
```
