### ISSUE TITLE
Too much recursion error for self referencing object in props

### ISSUE THREAD

**Issue by hugoattal** [histoire-dev/histoire#118]
### Describe the bug

When you use a self referencing object as a prop for a component, you get this error

![image](https://user-images.githubusercontent.com/4563971/172065356-087c664f-fad9-4e4c-b3e6-d020c7e9d4bc.png)
![image](https://user-images.githubusercontent.com/4563971/172065362-886d0759-fd18-4da6-8955-f3833ca6d094.png)

### Reproduction

Example of self referencing object:

```ts
const a = {}
const b = {}

a.child = b;
b.parent = a;
```

### System Info

```shell
-
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
I think we can check for already visited objects quite easily with a Set:

```ts
const seen = new Set()

// ...

// Check
if (!seen.has(obj)) {
  seen.add(obj)
  // ...
}
```
