### ISSUE TITLE
TypeError: CSS.supports is not a function

### ISSUE THREAD

**Issue by throrin19** [histoire-dev/histoire#122]
### Describe the bug

When I try to use histoire with vuetify v3, I have this error on build stories :  

```
Error while collecting story /Users/user/projects/test-vue/stories/components/AqLoadingScreen.story.vue:
TypeError: CSS.supports is not a function
    at file:///Users/user/projects/test-vue/node_modules/vuetify/lib/util/globals.mjs:4:57
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async ViteNodeRunner.interopedImport (file:///Users/user/projects/test-vue/node_modules/vite-node/dist/client-e36231b1.js:176:17)
    at async ViteNodeRunner.directRequest (file:///Users/user/projects/test-vue/node_modules/vite-node/dist/client-e36231b1.js:119:19)
    at async ViteNodeRunner.cachedRequest (file:///Users/user/projects/test-vue/node_modules/vite-node/dist/client-e36231b1.js:73:12)
    at async request (file:///Users/user/projects/test-vue/node_modules/vite-node/dist/client-e36231b1.js:95:21)
    at async /Users/user/projects/test-vue/src/plugins/vuetify.js:10:31
    at async ViteNodeRunner.directRequest (file:///Users/user/projects/test-vue/node_modules/vite-node/dist/client-e36231b1.js:159:5)
```

### Reproduction

to reproduce, add this in your histoire.setup.js :  

```js
import { createVuetify } from 'vuetify';

export const setupVue3 = defineSetupVue3(({ app, story, variant }) => {
    const vuetify = createVuetify();

    app.use(vuetify);
}
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 24.14 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Edge: 102.0.1245.30
    Firefox: 91.0.2
    Firefox Developer Edition: 69.0
    Safari: 15.5
  npmPackages:
    @vitejs/plugin-vue: 2.3.3 => 2.3.3 
    histoire: 0.7.2 => 0.7.2 
    vite: 2.9.9 => 2.9.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Naybnet** [comment]
Hi ! I have the same issue and found a bug report in vuetify3 here : https://github.com/vuetifyjs/vuetify/issues/14749 but the suggesting fixes seem to be adapted to unit test so I got stuck with the error that comes after `TypeError: Unknown file extension ".css`.

**Comment by snakeshift** [comment]
same error! thank you
