### ISSUE TITLE
Boolean state variables sometimes get broken

### ISSUE THREAD

**Issue by cyberbobs** [histoire-dev/histoire#131]
### Describe the bug

When the state contains multiple boolean variables (with controls attached to them), those fields values sometimes get replaced with empty object. The problem is unstable in reproduction and may need several page refreshes to show.

It's less likely to reproduce this if there's less than three boolean fields in `state` or if we don't mix string and boolean fields.

To reproduce, expand the preview panel on Stackblitz so the controls get visible. Every once in a while properties `frontIcon` and `backIcon` start to contain `{}` instead of `false`, `HstCheckbox` controls become checked and prop type validation warning appears in console.

### Reproduction

https://stackblitz.com/edit/node-ebgyvm?file=src/components/VsButton.story.vue

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz
    Memory: 4.11 GB / 11.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.12.1 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 100.0.2
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    histoire: ^0.7.3 => 0.7.3 
    vite: ^2.9.10 => 2.9.10
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirtan403** [comment]
I think I have the same issue.. When we have multiple boolean props, the first one is rendered as the switch in the props and others are of type json.

This is how our boolean props look like:

![image (29)](https://user-images.githubusercontent.com/7900938/172795474-20cbc64f-6ea8-41b7-bd6f-55291eda3585.png)

This is what we get in the histoire:
![image (28)](https://user-images.githubusercontent.com/7900938/172795580-265b5de8-765a-459e-a0fe-433e8fd9f977.png)

If we swap the 2 boolean props, the first prop is getting rendered as boolean and other is showing to enter a JSON in the histoire.
