### ISSUE TITLE
Story grid layout duplicates components when viewing story the second time

### ISSUE THREAD

**Issue by lukasjuhas** [histoire-dev/histoire#144]
### Describe the bug

When visitng a story page for the first time - all looks great as intended:
<img width="975" alt="Screenshot 2022-06-21 at 16 04 10" src="https://user-images.githubusercontent.com/5247674/174819288-9cc47ae5-75a0-4207-aa6a-bf087385767f.png">

If I navigate to another page, e.g. Tailwind and then come back to the previous story I viewed, all components are duplicated:
<img width="947" alt="Screenshot 2022-06-21 at 16 04 15" src="https://user-images.githubusercontent.com/5247674/174819324-048f4a45-ee5a-4405-ac07-fd9acafd6ecf.png">

I did not notice this happening in other modes apart from grid layout.

Video:

https://user-images.githubusercontent.com/5247674/174820866-6a3ee6a7-57db-495f-b6a4-34e3e28d8ced.mp4

### Reproduction

- GH Pages: https://lukasjuhas.github.io/histoire-ghpages-repro/
- Repo: https://github.com/lukasjuhas/histoire-ghpages-repro
- Story: https://github.com/lukasjuhas/histoire-ghpages-repro/blob/main/src/components/Button.story.vue

### System Info

```shell
Please see repro repo.
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antony-k1208** [comment]
We are experiencing the same bug. 

It seems to be related to the same component on different story variants. But I am not 100% sure. Maybe just a simple component recycling issue? Not using the key prop? 

https://vue3.examples.histoire.dev/story/src-components-basebutton-story-vue

Start here and click on "HugeGrid" in the sidebar. Go Back to "BaseButton" and again to "HugeGrid". Now you can see that some of the button components get reused.

**Comment by lukasjuhas** [comment]
@antony-k1208 This has been fixed, have you tried a more recent version of histoire? It was fixed for us by a fix from @Akryum.

**Comment by Akryum** [comment]
@antony-k1208 Looks like it's a different problem, could you open a new issue about it? Thank!
