### ISSUE TITLE
Global CSS leaks out of iframe

### ISSUE THREAD

**Issue by cyberbobs** [histoire-dev/histoire#147]
### Describe the bug

Even with one story running in single iframe mode injected [global css](https://histoire.dev/guide/config.html#global-js-and-css) leaks out from iframe to Histoire UI itself.

### Reproduction

https://stackblitz.com/edit/node-hpmcus?file=src/histoire.setup.js

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i7-3687U CPU @ 2.10GHz
    Memory: 2.48 GB / 11.40 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.15.1 - /usr/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.12.1 - ~/.npm-packages/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    histoire: ^0.7.8 => 0.7.8 
    vite: ^2.9.12 => 2.9.12
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
This is expected as you can have stories in the same context (not inside an iframe) and the controls are always in the main context.

**Comment by svedue** [comment]
Is this really a wanted behaviour? I'm working on a design-lib based on https://www.beercss.com/. 
Beercss' css brings styles on :root level leaving histoire ui unusable. Even with a single story in iFrame mode.
Is there a workaround?
