### ISSUE TITLE
Add Global Decorator for stories

### ISSUE THREAD

**Issue by throrin19** [histoire-dev/histoire#150]
### Clear and concise description of the problem

To describe some components, We have to made complexe and redondant templating to include the component inside a story (ex : with vuetify, add the VApp, VContent, VRow, ...)

But for each stories, if we made that, we have to change the source to show only our component and not the complexe decorator template.

### Suggested solution

Add the possibility to configure a global decorator for :  

- All histoire config (in the `histoire.setup.js` ?
- specific story

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by cjshearer** [comment]
The any usage of histoire with vuetify will realistically need this, as [each component's theming depends on being wrapped in v-app](https://vuetifyjs.com/en/components/application/). For example, a text field will be missing it's red error color on the error message if v-app is not supplied.

**Comment by Michael-372** [comment]
A way to wrap everything with v-app and still auto-detect props would be an amazing feature.

**Comment by Michael-372** [comment]
As a follow up to this and a workaround until this feature is added. I was able to get the vuetify styling AND the auto-detect props working in Histoire by using div's with the same classes that Vuetify uses. I had tried using the v-app, v-main, v-container components but histoire was auto-detecting the v-app props. By converting to use divs, it seems to be pulling from the first actual component it finds:

```html
<template>
  <Story>
    <Variant title="default">
      <div
        class="v-application v-theme--light v-layout v-layout--full-height v-locale--is-ltr"
      >
        <div class="v-main">
          <div class="v-container">
            <v-autocomplete
              chips
              multiple
              closable-chips
              no-filter
            />
          </div>
        </div>
      </div>
    </Variant>
  </Story>
</template>
```

**Comment by floroz** [comment]
The Global Decorator would be extremely useful. Many projects make use of the "Provider" pattern and we've been considering migrating away from Storybook to Histoire, but unable to do so until we have [a similar featureto Storybook decorators](https://storybook.js.org/docs/vue/writing-stories/decorators#context-for-mocking).

**Comment by Akryum** [comment]
Fixed in https://github.com/Akryum/histoire/commit/9f29c19
