### ISSUE TITLE
Registration of Component Globally issue. Failed to resolve component

### ISSUE THREAD

**Issue by jay-p-b-7span** [histoire-dev/histoire#158]
### Describe the bug

In histoire.setup.js file, I have registered Components globally using app.component API. But due to some bug, I get Vue Warn. I have attached Screenshot. 
![image](https://user-images.githubusercontent.com/93135924/176991075-fd5af99b-e06b-43a3-b659-860da6f7affa.png)

### Reproduction

URL https://stackblitz.com/edit/histoire-vue3-starter-vcat2n?file=src/CartTotal.story.vue

Component name : CartTotal 

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Memory: 4.75 GB / 15.38 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.1.4 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 101.0.1
  npmPackages:
    @vitejs/plugin-vue: ^2.3.3 => 2.3.3 
    histoire: ^0.7.8 => 0.7.8 
    vite: ^2.9.12 => 2.9.12
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by leifmarcus** [comment]
@jay-p-b-7span Seems like the `defineSetupVue3` function is called later then the first elements are created. I have the same issue in version `0.7.9`.

**Comment by jay-p-b-7span** [comment]
Thanks @Akryum  For fixing Bug. :+1:

**Comment by bart-1990** [comment]
I'm experiencing the same issue with current package.json

```
{
	"name": "histoire-example-vue3",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"story:dev": "histoire dev",
		"story:build": "histoire build",
		"story:preview": "histoire preview"
	},
	"dependencies": {
		"vue": "^3.2.31"
	},
	"devDependencies": {
		"@histoire/plugin-vue": "^0.11.0",
		"@vitejs/plugin-vue": "^3.0.1",
		"autoprefixer": "^10.4.7",
		"histoire": "^0.11.0",
		"tailwindcss": "^3.0.24",
		"vite": "^3.0.0"
	}
}
```

runtime-core.esm-bundler.js:38 [Vue warn]: Failed to resolve component: MyComp
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
