### ISSUE TITLE
Unknown file extension ".css"

### ISSUE THREAD

**Issue by cunzaizhuyi** [histoire-dev/histoire#160]
### Describe the bug

when i use vant toast component, i need import toast's css; 
but error happens in the terminal.  the custom script is 'npm run story:dev'; 

### Reproduction

`
import 'vant/es/toast/style';
`
in any xxx.story.vue

### System Info

```shell
v0.7.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
You can add `viteNodeInlineDeps: [/vant/]` to your `histoire.config.ts` config.

**Comment by cunzaizhuyi** [comment]
> You can add `viteNodeInlineDeps: [/vant/]` to your `histoire.config.ts` config.

it works, thanks

**Comment by Akryum** [comment]
This should be fixed in 0.8 as it no longer run the setup file on the collect server.
