### ISSUE TITLE
variant/story config to deactivate auto-detected component props

### ISSUE THREAD

**Issue by leifmarcus** [histoire-dev/histoire#177]
### Clear and concise description of the problem

Currently all pages that are created with the stories will have the auto-detected properties of the component. Sometimes it might be better, to not show all the properties, but only some, that you want to expose with the `<template #controls>`  option.

### Suggested solution

As I imagine it at the moment, it would be possible, to extend the `VueStoryProps` and `VueVariantProps` with a `config` object that can be passed to a story.

```html
<Story :config="{ hideAutoProps: true }">
...
</Story>
```

The advantage of a config property is, that it can be extended with other properties in the future, that might be also nice to have like the component name casing for the source code which is `PascalCase` by default, but some project might want to have `kebab-case` for component names in templates.

### Alternative

Another solution would be to create a boolean property on the `Story` and the `Variant` which will show the auto-detected properties by default and hide it, if set to `true`.

```html
<Story hide-auto-props>
...
</Story>
```

### Additional context

When dealing with more complex component libraries, you sometimes need to wrap your component inside another in order to get a certain functionality. In this case the props from the wrapped component would be always shown as auto-detected properties. In this case it would be nice to deactivate the auto properties and define custom ones for the component, that is displayed.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by leifmarcus** [comment]
I was just thinking again about it and as the properties are also part of the layout, it might also be an option, to integrate the option for not showing the props into the `StoryLayout` property. The disadvantage would be, that the layout would then be only available on the Story level.

**Comment by Akryum** [comment]
Let's have a  `auto-props-disabled` prop on Variant (they are automatically inherited from Story) :)

**Comment by leifmarcus** [comment]
@Akryum I think, my proposals are not really thought through, as I'm not so into the details of your implementation. I felt like, it is quite an easy topic and I’m pretty sure you will find the right way of implementing it ;) But anyways, thanks for implementing it. I'm looking forward.
