### ISSUE TITLE
Grid layout: Background picker + Open variant in new tab

### ISSUE THREAD

**Issue by Lyokolux** [histoire-dev/histoire#184]
### Clear and concise description of the problem

Using the grid layout disable the viewport size, `background-color` picker and the "Open Variant in new tab"

Currently:
<img width="776" alt="image" src="https://user-images.githubusercontent.com/29046067/179700054-2fbf752c-47db-4266-91a5-8026aad337ba.png">

With meow-component and expected options on the top right:
<img width="765" alt="image" src="https://user-images.githubusercontent.com/29046067/179700094-80c38ddf-6ceb-4f6f-a73d-ada40662cf56.png">

### Suggested solution

Options "Background Color" and "Open variant in new tab" could be available for every variant in grid layout

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Akryum** [comment]
Implemented in e828f8cbcdee2dd0201f407c95d9a63bb9d569ff and b2b05836fb0ebbd39c4e1a73bb72cc1baec1c6ce
