### ISSUE TITLE
Display default values/initial state of props in the auto props controls

### ISSUE THREAD

**Issue by awacode21** [histoire-dev/histoire#191]
### Clear and concise description of the problem

Currently when defining variants of a component and setting the prop values for the components the component gets rendered correctly but the auto generated prop controls are always empty. They are not prefilled with the initial prop state of the component.

When you want to have controls that get filled with the default/initial prop values you always need to define custom controls. So you end up with doubled controls basically doing the same.

### Suggested solution

I would suggest to set the default props value/initial state on the auto generated props

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by gr33nwhal3** [comment]
Any news about this issue ?

**Comment by wvffle** [comment]
Joining to the waitlist!

**Comment by sn00k** [comment]
Also awaiting news on this

**Comment by rockymontana** [comment]
Joining the waitlist too

**Comment by lateek35** [comment]
This will help clean a lot of boilerplate code so we could use the auto detection solely.
