### ISSUE TITLE
Support deployment on non-root web server paths

### ISSUE THREAD

**Issue by anoack93** [histoire-dev/histoire#195]
### Clear and concise description of the problem

As a developer using Histoire I want to deploy it as a static web application on GitLab Pages and other targets which use non-root web server paths for deployment.

When deploying with Gitlab Pages, the Histoire build artifacts are available under a path which looks like the following:

https://foo.gitlab.some-company.com/bar/

As Histoire references assets like this:

```html
<script type="module" src="/assets/bundle-main.62587cd2.js"></script>
```

The leading / in src attribute means that these assets have to be deployed on the webserver root. In our case this is not possible.

### Suggested solution

Storybook.js for example references assets without a leading slash and thus it works with relative paths.

However, I added a build step where leading slashes are removed from index.html and __sandbox.html, but that was 
not enough, as the story navigation is also using links which assume that the application is running on the web server root.

There might be even other obstacles with paths I didn't discover yet.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Akryum** [comment]
Could you try setting the `base` through the `vite` option in Histoire config?

```ts
import { defineConfig } from 'histoire'

export default defineConfig({
  vite: {
    base: '/some-repo/',
  }
})
```

**Comment by anoack93** [comment]
@Akryum yes that configuration has worked, as I only want to specify a different base for the CI pipeline and not for local development, I used an environment variable 

```ts
import { defineConfig } from 'histoire';

export default defineConfig({
  vite: {
    base: process.env.HISTOIRE_BASE || '/',
  },
});
```

Thank you very much

**Comment by waldemarennsaed** [comment]
> @Akryum yes that configuration has worked, as I only want to specify a different base for the CI pipeline and not for local development, I used an environment variable
> 
> ```ts
> import { defineConfig } from 'histoire';
> 
> export default defineConfig({
>   vite: {
>     base: process.env.HISTOIRE_BASE || '/',
>   },
> });
> ```
> 
> Thank you very much

Does this work @anoack93 ? I also need to set a different path in my CI build and the `/` base when locally.

How does histoire actually read the `process.env.HISTOIRE_BASE`? Can I just define a `.env` file or do I have to do some additional vite-config?

**Comment by anoack93** [comment]
@waldemarennsaed yes it worked. I didn't test it with the latest histoire version though.

Environment variables are a concept which exists on the operating system level, usually you are setting them in the terminal (eg. bash/shell) when working locally.

In node.js process.env contains all environment variables which have been set when starting the node application.
NPM packages like dotenv can import env variables from a file.

However, in GitLab CI for example (and probably also in other CI/CD tools) you can set them with the "variables" option

```yaml
pages:
  stage: deploy
  extends: .node-frontend-job
  variables:
    HISTOIRE_BASE: /$CI_PROJECT_NAME/
  script:
    - npm run build:histoire
    # nuxt also has a public directory, we need to remove it first
    - rm -r ./public
    - mv .histoire/dist ./public
  artifacts:
    paths:
      - public
```

**Comment by waldemarennsaed** [comment]
@anoack93 unfortunately that doesn't work for me (using GitLab) - either I give it `/` (since GitLab automatically prefixes the path like `my-org.gitlab.io/path/to/repo/`) - then it just references to `https://my-org.gitlab.io/assets/styles.css` - or I give it the project-path (or even including the domain) and it duplicates the address for me, like `https://my-org.gitlab.io/path/to/repo/path/to/repo/styles.css` or `https://my-org.gitlab.io/path/to/repo/https://my-org.gitlab.io/path/to/repo/styles.css`

I have not figured out a solution yet.
