### ISSUE TITLE
[Tailwind design tokens] nested custom colors not being rendered

### ISSUE THREAD

**Issue by rromanv** [histoire-dev/histoire#200]
### Describe the bug

On my tailwind config, if I use nested colors names historie doesn't resolve them, but tailwind does.

On the reproduction link, I created 3 variants of the BaseButton; all colors work there, but on the tailwind rendered configuration, the nested "dontWork" colors are not showing correctly.

Also, when I tried to copy the missing color from the copy button, it saved as `[object Object]` instead of the actual content, similar to what discussion #182 described.

tailwind.config.js
```js
module.exports = {
  content: ['./src/**/*.{html,js,vue}'],
  theme: {
    colors: {
      prefix: {
        work: '#ED7623',
        dontWork: {
          DEFAULT: '#552D81',
          variant: '#873299',
        },
      },
    },
  },
}
```

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-tw-nested-color-bug?file=tailwind.config.js

### System Info

```shell
System:
    OS: Linux 5.10 Arch Linux
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Memory: 48.74 GB / 49.58 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.6.0/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v18.6.0/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^3.0.0 => 3.0.1
    histoire: ^0.8.1 => 0.8.4
    vite: ^3.0.0 => 3.0.2
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
This is currently a limitation of the auto-generated tokens. We need to add support for additional nesting in colors.

**Comment by sun0day** [comment]
I can offer a PR@Akryum
