### ISSUE TITLE
TypeError: __vite_ssr_import_12__.default is not a function

### ISSUE THREAD

**Issue by tcitworld** [histoire-dev/histoire#204]
### Describe the bug

ViteNodeRunner wants to use `@absinthe/socket` (which might not be the cleanest). I tried to use `viteNodeInlineDeps` without success. Removing the call to this dependency makes it work properly.

```
Error while collecting story [...]/src/components/Post/PostListItem.story.vue:
TypeError: __vite_ssr_import_12__.default is not a function
    at @jumpn/utils-composite:14:4251
    at async ViteNodeRunner.directRequest (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:159:5)
    at async ViteNodeRunner.cachedRequest (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:73:12)
    at async request (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:95:21)
    at async @absinthe/socket:7:31
    at async ViteNodeRunner.directRequest (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:159:5)
    at async ViteNodeRunner.cachedRequest (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:73:12)
    at async request (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:95:21)
    at async [...]absinthe-socket-link.ts:3:31
    at async ViteNodeRunner.directRequest (file:///[...]/node_modules/vite-node/dist/client-e36231b1.js:159:5)
```

### Reproduction

Use this repo: https://github.com/tcitworld/histoire-absinthe-socket and run `story:dev`

### System Info

```shell
  System:
    OS: Linux 5.18 Fedora Linux 36.20220731.0 (Silverblue)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 8.03 GB / 15.32 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.0/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Firefox: 102.0
  npmPackages:
    @histoire/plugin-vue: ^0.9.0 => 0.9.0 
    @vitejs/plugin-vue: ^2.3.2 => 2.3.3 
    histoire: ^0.9.0 => 0.9.0 
    vite: ^2.9.0 => 2.9.14 
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
I've taken a look at this, and unfortunately it seems that the `@absinthe/*` packages your are using depend on (very) old version of `babel-runtime` (which is now `@babel/runtime`) and on `graphql@14` which are both incompatible with Node ESM (fixed in `@babel/runtime` and `graphql@15`).
