### ISSUE TITLE
Cannot use unnested colors in theme as documented

### ISSUE THREAD

**Issue by FreekVR** [histoire-dev/histoire#205]
### Describe the bug

If I write a `theme.colors`   as llisted in the documentation I get an error  `Internal server error: Cannot read property 'color' of null`. It seems to be the case that the following bit of code assumes that colors are always nested eg. `color.slate.50`

```
                // Colors
                for (const color in ctx.config.theme?.colors ?? {}) {
                    for (const key in ctx.config.theme.colors[color]) {
                        // Error is thrown below...
                        css += `--_histoire-color-${color}-${key}: ${parseColor(ctx.config.theme.colors[color][key]).color.join(' ')};`;
                    }
                }
 ```

### Reproduction

Copy-paste the following config
```
// histoire.config.ts

export default defineConfig({ 
  theme: {
    colors: {
      primary: '#FF0000'
    }
  }
})
```

Run `story:dev`

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics
    Memory: 6.84 GB / 13.58 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
> If I write a theme.colors as llisted in the documentation

Your reproduction is not was is documented.

**Comment by Akryum** [comment]
https://histoire.dev/guide/config.html#colors
