### ISSUE TITLE
HstSelect control throws error

### ISSUE THREAD

**Issue by tbusser** [histoire-dev/histoire#206]
### Describe the bug

When writing a story and using the HstSelect control, the story stops working. The following error is shown in the console:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/5519027/181109601-f057915b-8497-4727-96ff-0b305be60576.png">

In addition, the `HstSelect` has no intellisense in VSCode. 
<img width="520" alt="image" src="https://user-images.githubusercontent.com/5519027/181110074-cfbb660a-d940-43b1-8efe-dfc147c357a5.png">

### Reproduction

I've created a new Vue3 project using npm init vue@next, afterwards I've added Histoire to the project using the steps described in the [documentation](https://histoire.dev/guide/getting-started.html). To get the project to run I had to downgrade `vite` and `@vitejs/plugin-vue` as Histoire doesn't yet support Vite 3.

I've copied the `BaseButton.vue` component from the histoire example and pasted it into the project I just created.

The repository can be found [here](https://github.com/tbusser/histoire-select)

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 693.53 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Edge: 103.0.1264.71
    Firefox: 101.0
    Safari: 15.5
    Safari Technology Preview: 16.0
  npmPackages:
    @vitejs/plugin-vue: ^2.3.2 => 2.3.3
    histoire: ^0.8.4 => 0.8.4
    vite: ^2.9.12 => 2.9.12
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Marianna-Ma** [comment]
I came over with the same problem, it seems that the HstSelect doesn't work even in the online demo. Have you got any idea?

**Comment by Akryum** [comment]
Looks like it works [here](https://vue3.examples.histoire.dev/story/src-components-controls-story-vue?variantId=src-components-controls-story-vue-0)  and [here](https://controls.histoire.dev/story/src-components-select-hstselect-story-vue) 🤔

**Comment by Akryum** [comment]
> In addition, the HstSelect has no intellisense in VSCode.

Looks like the definition is missing [here](https://github.com/histoire-dev/histoire/blob/e4254ed026e8afe107776bf6ce40991808d3d2b2/packages/histoire-plugin-vue/components.d.ts#L130-L143) indeed

**Comment by tbusser** [comment]
> Looks like it works [here](https://vue3.examples.histoire.dev/story/src-components-controls-story-vue?variantId=src-components-controls-story-vue-0) and [here](https://controls.histoire.dev/story/src-components-select-hstselect-story-vue) 🤔

Yeah, that is what's so odd. On the example website it works like a charm. When I run the Vue3 example on my machine it also works. But when I take the `BaseButton` component and past it into a fresh Vue3 project with Histoire installed from NPM it fails.

**Comment by alvarosabu** [comment]
@Akryum I got the same error on a project where the option was reactive, but I tried to create a repro on Stackblitz and couldn't reproduce anymore, it's something related with the floating-vue
