### ISSUE TITLE
Error while collecting story X - CommonJS module

### ISSUE THREAD

**Issue by andreataglia** [histoire-dev/histoire#220]
### Describe the bug

On some story MyStory.story.vue i import a vue component that relies on the @apollo/client package and this is what i get as error:

`Error while collecting story ... MyStory.story.vue
file:/// ... node_modules/@apollo/client/utilities/globals/fix-graphql.js:1
import { remove } from "ts-invariant/process/index.js";

SyntaxError: Named export 'remove' not found. The requested module 'ts-invariant/process/index.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'ts-invariant/process/index.js';
const { remove } = pkg;

at ModuleJob._instantiate (node:internal/modules/esm/module_job:127:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:193:5)
    at async Promise.all (index 0)
`

the story is not shown in the Histoire UI, while the others are.

Other than this issue i'm having, i've had a great experience with Histoire. Migrating from storybook to this. 100 times better <3

### Reproduction

Maybe this is enough. I'll add if needed.

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 9.34 GB / 15.27 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Brave Browser: 103.1.41.100
    Firefox: 103.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Could you try adding the `ts-invariant` package to Vite optimizeDeps include config?

**Comment by Akryum** [comment]
A runnable reproduction as a stackblitz or a clonable repo would help a lot, thanks!

**Comment by andreataglia** [comment]
seems to be solved by using vite 3+. i had vite 2.x using _@rollup/plugin-commonjs_ which was apparently causing the issue. i guess it can be closed. Thanks a lot for the prompt answer and all the best with this crazy useful project! I hope i'll manage to find some spare time to contribute

**Comment by Akryum** [comment]
> I hope i'll manage to find some spare time to contribute

That would be rad :100:
