### ISSUE TITLE
'canvas.getContext is not a function' error  occured when i use lottie

### ISSUE THREAD

**Issue by kyumoon** [histoire-dev/histoire#233]
### Describe the bug

'canvas.getContext is not a function' error  occured
when i use lottie

<img width="1196" alt="스크린샷 2022-08-11 오후 5 02 00" src="https://user-images.githubusercontent.com/42454603/184090760-d8509ed0-15dc-4830-9580-a8d0baa4c291.png">

### Reproduction

https://github.com/histoire-dev/histoire/compare/main...kyumoon:histoire:main

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 242.02 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Safari: 15.4
    Safari Technology Preview: 15.4
  npmPackages:
    @histoire/plugin-vue: workspace:* => 0.9.6 
    @vitejs/plugin-vue: ^3.0.1 => 3.0.1 
    histoire: workspace:* => 0.9.6 
    vite: ^3.0.5 => 3.0.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by megasanjay** [comment]
+1 Seems like a potential issue with vite?

**Comment by jntn** [comment]
I get same issue when using [Konva](https://konvajs.org/)

**Comment by Akryum** [comment]
Stories are collecting in a Node environment with a DOM stub (happy-dom). Canvas is unfortunately not supported in Node. Maybe we can have a flag to put a condition in the `onMounted()`?

**Comment by Akryum** [comment]
See: https://github.com/histoire-dev/histoire/blob/e3cd92a034ad5557d130f2c612d8ad4257892ca1/examples/vue3/src/components/LottieAnimation.story.vue#L6

**Comment by jntn** [comment]
Works like a charm! Thanks!

**Comment by reslear** [comment]
also for custom vue plugin use `defineAsyncComponent`: 

```ts
  app.component(
    'Vue3Lottie',
    defineAsyncComponent(() =>
      import('@reslear/vue3-lottie').then((m) => m.Vue3Lottie)
    )
  )
```

**Comment by lud-hu** [comment]
I get the same error in my nuxt project:
```
Error while collecting story /repo/components/01_atoms/TheButton.story.vue:
TypeError: Cannot set properties of null (setting 'fillStyle')
    at /repo/node_modules/lottie-web/build/player/lottie.js:1320:21
    at /repo/node_modules/lottie-web/build/player/lottie.js:1323:6
    at /repo/node_modules/lottie-web/build/player/lottie.js:1540:4
    at /repo/node_modules/lottie-web/build/player/lottie.js:2:83
    at /repo/node_modules/lottie-web/build/player/lottie.js:5:3
    at ViteNodeRunner.runModule (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:342:11)
    at ViteNodeRunner.directRequest (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:326:16)
    at async ViteNodeRunner.cachedRequest (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:189:14)
    at async ViteNodeRunner.dependencyRequest (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:223:12)
    at async /repo/components/01_atoms/TheAnimation.vue:4:31
```

What can I do about this in my nuxt project? None of my stories do import or use the TheAnimation component rendered in the error log.

**Comment by qmpwwsd** [comment]
> I get the same error in my nuxt project:
> 
> ```
> Error while collecting story /repo/components/01_atoms/TheButton.story.vue:
> TypeError: Cannot set properties of null (setting 'fillStyle')
>     at /repo/node_modules/lottie-web/build/player/lottie.js:1320:21
>     at /repo/node_modules/lottie-web/build/player/lottie.js:1323:6
>     at /repo/node_modules/lottie-web/build/player/lottie.js:1540:4
>     at /repo/node_modules/lottie-web/build/player/lottie.js:2:83
>     at /repo/node_modules/lottie-web/build/player/lottie.js:5:3
>     at ViteNodeRunner.runModule (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:342:11)
>     at ViteNodeRunner.directRequest (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:326:16)
>     at async ViteNodeRunner.cachedRequest (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:189:14)
>     at async ViteNodeRunner.dependencyRequest (file:///repo/node_modules/histoire/node_modules/vite-node/dist/client.mjs:223:12)
>     at async /repo/components/01_atoms/TheAnimation.vue:4:31
> ```
> 
> What can I do about this in my nuxt project? None of my stories do import or use the TheAnimation component rendered in the error log.

Same thing but with Konva. I don't use it in stories, but it all broke: [My issue](https://github.com/histoire-dev/histoire/issues/786)
