### ISSUE TITLE
Docs files

### ISSUE THREAD

**Issue by Akryum** [histoire-dev/histoire#237]
To support more use cases (such as documenting `.story.svelte` files - #86), Histoire will support adding documentation as `.story.md` files that will automatically loaded into the corresponding story.

Example:

- `BaseButton.story.svelte`
- `BaseButton.story.md`

There will also be a new `docsFile` prop added to `Story` to specify a custom path to the `md` file.

- [x] Add docs to story with related md file
- [x] Standalone page

**Comment by Akryum** [comment]
Putting a corresponding `.md` file next to a story populates the `Docs` tab:

![image](https://user-images.githubusercontent.com/2798204/184449979-91488720-5e27-4f02-b360-7715a113a6a2.png)
![image](https://user-images.githubusercontent.com/2798204/184450003-8782a635-c52e-4ef3-a4c1-36dbfa6f3ba1.png)

**Comment by Akryum** [comment]
Putting a standalone `.story.md` file creates a virtual story with `docsOnly: true`:

![image](https://user-images.githubusercontent.com/2798204/184450091-e34e6d6c-bd13-43c4-86ba-9f944ed12b74.png)
![image](https://user-images.githubusercontent.com/2798204/184450104-14da7079-d7aa-4bb3-994f-5c9f9f1a7f78.png)

**Comment by rijkvanzanten** [comment]
Sorry to ping on an old issue, but whatever happened to:

> There will also be a new docsFile prop added to Story to specify a custom path to the md file.

? I can't seem to find any docs or trace about this prop in the referenced commit or docs, which makes me worried it wasn't actually implemented? Is that something you'd accept a PR for @Akryum?
