### ISSUE TITLE
SvelteKit demo?

### ISSUE THREAD

**Issue by oneezy** [histoire-dev/histoire#241]
### Clear and concise description of the problem

The recenly added Svelte 3 demo provides a way to use Svelte with Histoire but doesn't demo **SvelteKit** with Histoire.

I've attempted to add Histoire to SvelteKit without success.

### Suggested solution

Could you guys put a demo together based on the SvelteKit starter skeleton app?

https://kit.svelte.dev/

```
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by narcisoli** [comment]
Maybe is not the best solution but this is my workaround for sveltekit:
![image](https://user-images.githubusercontent.com/21956394/185134907-3dd0d023-d8fb-47d8-bf3d-d547446aaf33.png)

**Comment by oneezy** [comment]
@narcisoli , does this allow you to import Sveltekit specific modules in components (i.e. `$path`) without breaking Histoire stories?

I created #384 to try and get this resolved
