### ISSUE TITLE
Nuxt + Histoire doesn't work

### ISSUE THREAD

**Issue by Bobakanoosh** [histoire-dev/histoire#244]
### Describe the bug

- I have made a fresh nuxt project on stackblitz (and locally via Nuxt's "getting started" instructions)
- I then installed histoire while following the getting started for nuxt
- I then created a basic `Button.vue` and `Button.story.vue`, and got the following errors in console when clicking on the story:
![image](https://user-images.githubusercontent.com/10647192/184574622-3f0cc077-0050-450a-8345-c57729ebae5c.png)

For used package manager - I use `pnpm` locally but the reproduction stackblitz uses `npm`

### Reproduction

https://stackblitz.com/edit/nuxt-starter-j2ib4c

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor
    Memory: 15.30 GB / 31.94 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (104.0.1293.54)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Lyokolux** [comment]
I get the same issue. I updated from Histoire 8.2 to latest 10.2 with Nuxt RC 8.


During the build:
```
Unexpected token (Note that you need plugins to import files that are not JavaScript)
file: /$histoire-generated-global-setup-resolved:9:13
 7:                 }
 8:               }
 9:             },export async function setupVue3 (payload) {
                 ^
10:               for (const setup of setupList) {
11:                 if (setup?.setupVue3) {
file:///Users/alexandre.guidoux/projects/ergosign-pixel-warriors/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:1858
        base = Object.assign(new Error(base.message), base);
```

In dev im Browser after the first load on click on a story:
```
Uncaught (in promise) SyntaxError: expected expression, got ',' [$histoire-generated-global-setup-resolved:9:13](<BASE_URL>/$histoire-generated-global-setup-resolved)
```
