### ISSUE TITLE
DOMException: Failed to execute 'postMessage' on 'Window': ()=>{var t;return{default:!0,controls:(t=n.controls)!=null?t:p.controls}} could not be cloned.

### ISSUE THREAD

**Issue by haleksandre** [histoire-dev/histoire#247]
### Describe the bug

Getting a `DOMException` when trying to use `getContext` to get the curent story & variant information.

```
sandbox.js:43 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>{var t;return{default:!0,controls:(t=n.controls)!=null?t:p.controls}} could not be cloned.
```
The deep clone seems to be causing the issue.
https://github.com/histoire-dev/histoire/blob/34669753cb018b6cff5bbb9963b2801b1efdf462/packages/histoire-app/src/app/components/story/StoryVariantSinglePreviewRemote.vue#L28

Possible solutions would be to fix what can't be cloned, looks like `toRawDeep` doesn't skip function? Or provide a `readable` store with these values?

### Reproduction

https://stackblitz.com/edit/histoire-svelte3-starter-xwewrr?file=src%2FBaseButton.story.svelte

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  npmPackages:
    @histoire/plugin-svelte: ^0.10 => 0.10.0 
    histoire: ^0.10.0 => 0.10.0 
    vite: ^3.0.0 => 3.0.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Fixed by https://github.com/histoire-dev/histoire/commit/0f5b40047efd15bda2946af1647a4563a38cebf3
