### ISSUE TITLE
Extending setupVue3 with a 3rd party plugin which utilises provide throws an error when injecting

### ISSUE THREAD

**Issue by antony-k1208** [histoire-dev/histoire#249]
### Describe the bug

Import a 3rd party package which uses Vue's `provide` function and register it inside the `setupVue3` function.

Use Vue's `inject` function or the `useXXX` composable of the library to inject the data inside a story.
Start histoire in dev mode and after collecting the stories you will see an error in your console, that you tried to inject something which wasn't provided (of course only if the library throws such an error). 

The strange thing is it seems to be available anyway. You can test this when you log the output of inject inside the story's `script` tag.

In prod there is no error whatsoever. Is there something different in dev than in prod? Maybe collecting dependencies and bundling it for a story is not 100% correct?

Maybe all the different Vue applications in histoire don't get access to the customised `setupVue3` body?

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-grkxtx?file=src/Toast.story.vue

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.25 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.volta/tools/image/node/16.15.0/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.5.5 - ~/.volta/tools/image/node/16.15.0/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Firefox: 96.0.1
    Safari: 15.6
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Currently the app setups aren't executed while collecting the stories (by executing the `.story.vue` components in node). This is to prevent errors related to importing css and other. We will improve this going forward!

This means you might see your error in the terminal when collecting happens, but there will be no errors in the book in your browser and the story should display correctly.

**Comment by Akryum** [comment]
Also note that all components are stubbed automatically during the collect process in Node.)
