### ISSUE TITLE
↗️ Auto "open browser" option

### ISSUE THREAD

**Issue by oneezy** [histoire-dev/histoire#257]
### Clear and concise description of the problem

I want an option that will automatically open up the browser window when starting `dev` server or `preview`

I typically use `--open` in my `package.json` scripts but when trying to use this with Histoire it did not work.

### Suggested solution

i.e.
```json
  "scripts": {
    "story:dev": "histoire dev --port 6006 --open",
    "story:build": "histoire build",
    "story:preview": "histoire preview --port 6006 --open"
  },
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by oneezy** [comment]
:laughing:  , right after i submitted feature request i figured out how to do it.

Vite can do this easily from within the `vite.config.js` file
```js
export default defineConfig({
  server: {
    open: '/' 
  }
})
```
https://vitejs.dev/config/server-options.html

**Comment by oneezy** [comment]
you may or may not want to reimplement this functionality for histoire

**Comment by Lyokolux** [comment]
> you may or may not want to reimplement this functionality for histoire so i'll leave open for now

Or document it on the histoire config page :)
