### ISSUE TITLE
Control reactivity issues on first page load

### ISSUE THREAD

**Issue by haleksandre** [histoire-dev/histoire#264]
### Describe the bug

When you load a page for the first time, the controls seem to only trigger reactivity once. Afterward the reactivity stop until you change variant or story. Once this page change happens it looks like controls are working as expected.

### Reproduction

https://stackblitz.com/edit/histoire-svelte3-starter-cucrx9?file=src%2FBaseButton.story.svelte

Load Histoire then go to base button story's page. Clicking disabled control on/off is working as expected.
Refresh button story's page. Clicking disabled control on/off is working only once, after the first control change it stop working until you navigate to a new page/variant & come back to base button story's page.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/plugin-svelte: ^0.10 => 0.10.5 
    histoire: ^0.10.0 => 0.10.5 
    vite: ^3.0.0 => 3.0.9
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sun0day** [comment]
Do I miss something? The reproduction you offer works fine in my browser.

**Comment by murongg** [comment]
> https://stackblitz.com/edit/histoire-svelte3-starter-cucrx9?file=src%2FBaseButton.story.svelte

Me too!

**Comment by murongg** [comment]
> Do I miss something? The reproduction you offer works fine in my browser.

Me too!

**Comment by haleksandre** [comment]
@sun0day @murongg are you using the disabled checkbox underneath the button or the one in the control panel?

The one that trigger reactivity only once on first page load is the one in the control panel, the other one underneath works as expected. You can even 'unfreeze' the one in the control panel by triggering reactivity on the one underneath the button.

**Comment by sun0day** [comment]
> @sun0day @murongg are you using the disabled checkbox underneath the button or the one in the control panel?
> 
> The one that trigger reactivity only once on first page load is the one in the control panel, the other one underneath works as expected. You can even 'unfreeze' the one in the control panel by triggering reactivity on the one underneath the button.

Ohoh, the disable checkbox in the control panel does have the problem.
