### ISSUE TITLE
Change the tailwind-olugin display in tree.file = 'path' view

### ISSUE THREAD

**Issue by BracketJohn** [histoire-dev/histoire#276]
### Clear and concise description of the problem

When using `tree.file: 'path'` in the config:
```ts
import { defineConfig } from 'histoire'
import { HstVue } from '@histoire/plugin-vue'
import { HstNuxt } from '@histoire/plugin-nuxt'

export default defineConfig({
  plugins: [
    HstVue(),
    HstNuxt(),
  ],
  tree: {
    file: 'path',
  },
})

```

The tailwind plugin shows up under `node_modules`:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/25911230/187622393-fb39f22f-97be-4bc4-b3b3-76804cb0bc39.png">

At first this raised the alarm bells for me and I thought that `histoire` crawled all of `node_module`s, after ignoring `node_module`s via `storyIgnored: ['node_modules'],` I learned that this is not the case, instead the plugin is just displayed that way.

### Suggested solution

Use a `plugins/` top level element to display plugins in `path` mode.

### Additional context

Thanks for the library, it's great and a really fresh breeze compared to configuring, maintaining and working with storybook (as of sb 6.5).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Akryum** [comment]
> Thanks for the library, it's great and a really fresh breeze compared to configuring, maintaining and working with storybook (as of sb 6.5).

Thanks! 🤗
