### ISSUE TITLE
Nuxt module doesn't isntall plugin

### ISSUE THREAD

**Issue by tobiasklemp** [histoire-dev/histoire#277]
### Describe the bug

I wrote a theme module which installs different ui packages like vuetify or windicss and takes a unified config object to have the same config on all of these libraries. However my module installs the nuxt modules and vue plugins of those libraries using nuxt/kit. This is working when running nuxt itself, but when i try to run it with histoire with the nuxrt plugin, the module itself is getting called but the plugins that it should install are not installed. 

### Reproduction

https://github.com/tobiasklemp/histoire-nuxt-modules

This minimal reproduction shows, that it is not possible to install plugins using nuxt kit.

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 184.15 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.5
npmPackages:
    @histoire/plugin-nuxt: ^0.10.7 => 0.10.7 
    @histoire/plugin-vue: ^0.10.7 => 0.10.7 
    histoire: ^0.10.7 => 0.10.7
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by arpadgabor** [comment]
Experiencing something similar with the `vue-i18n` plugin for Nuxt. The following message shows up in the browser console when loading Histoire.

```
Uncaught (in promise) SyntaxError: Need to install with `app.use` function
    createCompileError message-compiler.esm-bundler.js:54
    createI18nError vue-i18n.esm-bundler.js:100
    useI18n vue-i18n.esm-bundler.js:2219
    setup Article.vue:21
    callWithErrorHandling runtime-core.esm-bundler.js:155
    setupStatefulComponent runtime-core.esm-bundler.js:7186
    setupComponent runtime-core.esm-bundler.js:7141
    mountComponent runtime-core.esm-bundler.js:5493
    processComponent runtime-core.esm-bundler.js:5468
    patch runtime-core.esm-bundler.js:5058
    mountChildren runtime-core.esm-bundler.js:5254
    processFragment runtime-core.esm-bundler.js:5427
    patch runtime-core.esm-bundler.js:5051
    componentUpdateFn runtime-core.esm-bundler.js:5607
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5714
    callWithErrorHandling runtime-core.esm-bundler.js:155
    flushJobs runtime-core.esm-bundler.js:386
    promise callback*queueFlush runtime-core.esm-bundler.js:280
    queuePostFlushCb runtime-core.esm-bundler.js:302
    resolve runtime-core.esm-bundler.js:1401
    registerDep runtime-core.esm-bundler.js:1493
    promise callback*registerDep runtime-core.esm-bundler.js:1455
    mountComponent runtime-core.esm-bundler.js:5501
    processComponent runtime-core.esm-bundler.js:5468
    patch runtime-core.esm-bundler.js:5058
    mountChildren runtime-core.esm-bundler.js:5254
    processFragment runtime-core.esm-bundler.js:5427
    patch runtime-core.esm-bundler.js:5051
    componentUpdateFn runtime-core.esm-bundler.js:5607
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5714
    setupRenderEffect runtime-core.esm-bundler.js:5728
    mountComponent runtime-core.esm-bundler.js:5510
    processComponent runtime-core.esm-bundler.js:5468
    patch runtime-core.esm-bundler.js:5058
    componentUpdateFn runtime-core.esm-bundler.js:5607
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5714
    setupRenderEffect runtime-core.esm-bundler.js:5728
    mountComponent runtime-core.esm-bundler.js:5510
    processComponent runtime-core.esm-bundler.js:5468
    patch runtime-core.esm-bundler.js:5058
    componentUpdateFn runtime-core.esm-bundler.js:5607
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5714
    setupRenderEffect runtime-core.esm-bundler.js:5728
    registerDep runtime-core.esm-bundler.js:1476
    promise callback*registerDep runtime-core.esm-bundler.js:1455
    mountComponent runtime-core.esm-bundler.js:5501
    processComponent runtime-core.esm-bundler.js:5468
    patch runtime-core.esm-bundler.js:5058
    mountSuspense runtime-core.esm-bundler.js:1198
    process runtime-core.esm-bundler.js:1175
    patch runtime-core.esm-bundler.js:5064
    componentUpdateFn runtime-core.esm-bundler.js:5607
    run reactivity.esm-bundler.js:185
    update runtime-core.esm-bundler.js:5714
    setupRenderEffect runtime-core.esm-bundler.js:5728
    mountComponent runtime-core.esm-bundler.js:5510
    processComponent runtime-core.esm-bundler.js:5468
    patch runtime-core.esm-bundler.js:5058
    render2 runtime-core.esm-bundler.js:6229
    mount runtime-core.esm-bundler.js:4422
    mount runtime-dom.esm-bundler.js:1606
    mountStory MountStory.js:47
    setup MountStory.js:57
    callWithErrorHandling vue.runtime.esm-bundler.js:1993
    callWithAsyncErrorHandling vue.runtime.esm-bundler.js:2002
    __weh vue.runtime.esm-bundler.js:4525
    flushPostFlushCbs vue.runtime.esm-bundler.js:2196
    flushJobs vue.runtime.esm-bundler.js:2241
    promise callback*queueFlush vue.runtime.esm-bundler.js:2123
    queueJob vue.runtime.esm-bundler.js:2117
    effect vue.runtime.esm-bundler.js:7530
    triggerEffect vue.runtime.esm-bundler.js:987
    triggerEffects vue.runtime.esm-bundler.js:977
message-compiler.esm-bundler.js:54:18
```

This is how my `plugins/i18n.ts` file looks:

```
import { createI18n } from 'vue-i18n'
import ro from '~/locales/ro.json'

export default defineNuxtPlugin(({ vueApp }) => {
  console.log('here')
  const i18n = createI18n<[typeof ro], 'ro-RO'>({
    legacy: false,
    globalInjection: true,
    locale: 'ro-RO',
    messages: {
      'ro-RO': ro,
    },
  })

  vueApp.use(i18n)
})
```

It seems like we are never reaching that console log inside the plugin. Would help with this issue however I'm not sure how we can tap into the nuxt plugin loader.

**Comment by Lyokolux** [comment]
> Experiencing something similar with the `vue-i18n` plugin for Nuxt (v3 rc8). The following message shows up in the browser console when loading Histoire.
> 
> ```
> Uncaught (in promise) SyntaxError: Need to install with `app.use` function
>     createCompileError message-compiler.esm-bundler.js:54
>     createI18nError vue-i18n.esm-bundler.js:100
>     useI18n vue-i18n.esm-bundler.js:2219
>     setup Article.vue:21
>     callWithErrorHandling runtime-core.esm-bundler.js:155
>     setupStatefulComponent runtime-core.esm-bundler.js:7186
>     setupComponent runtime-core.esm-bundler.js:7141
>     mountComponent runtime-core.esm-bundler.js:5493
>     processComponent runtime-core.esm-bundler.js:5468
>     patch runtime-core.esm-bundler.js:5058
>     mountChildren runtime-core.esm-bundler.js:5254
>     processFragment runtime-core.esm-bundler.js:5427
>     patch runtime-core.esm-bundler.js:5051
>     componentUpdateFn runtime-core.esm-bundler.js:5607
>     run reactivity.esm-bundler.js:185
>     update runtime-core.esm-bundler.js:5714
>     callWithErrorHandling runtime-core.esm-bundler.js:155
>     flushJobs runtime-core.esm-bundler.js:386
>     promise callback*queueFlush runtime-core.esm-bundler.js:280
>     queuePostFlushCb runtime-core.esm-bundler.js:302
>     resolve runtime-core.esm-bundler.js:1401
>     registerDep runtime-core.esm-bundler.js:1493
>     promise callback*registerDep runtime-core.esm-bundler.js:1455
>     mountComponent runtime-core.esm-bundler.js:5501
>     processComponent runtime-core.esm-bundler.js:5468
>     patch runtime-core.esm-bundler.js:5058
>     mountChildren runtime-core.esm-bundler.js:5254
>     processFragment runtime-core.esm-bundler.js:5427
>     patch runtime-core.esm-bundler.js:5051
>     componentUpdateFn runtime-core.esm-bundler.js:5607
>     run reactivity.esm-bundler.js:185
>     update runtime-core.esm-bundler.js:5714
>     setupRenderEffect runtime-core.esm-bundler.js:5728
>     mountComponent runtime-core.esm-bundler.js:5510
>     processComponent runtime-core.esm-bundler.js:5468
>     patch runtime-core.esm-bundler.js:5058
>     componentUpdateFn runtime-core.esm-bundler.js:5607
>     run reactivity.esm-bundler.js:185
>     update runtime-core.esm-bundler.js:5714
>     setupRenderEffect runtime-core.esm-bundler.js:5728
>     mountComponent runtime-core.esm-bundler.js:5510
>     processComponent runtime-core.esm-bundler.js:5468
>     patch runtime-core.esm-bundler.js:5058
>     componentUpdateFn runtime-core.esm-bundler.js:5607
>     run reactivity.esm-bundler.js:185
>     update runtime-core.esm-bundler.js:5714
>     setupRenderEffect runtime-core.esm-bundler.js:5728
>     registerDep runtime-core.esm-bundler.js:1476
>     promise callback*registerDep runtime-core.esm-bundler.js:1455
>     mountComponent runtime-core.esm-bundler.js:5501
>     processComponent runtime-core.esm-bundler.js:5468
>     patch runtime-core.esm-bundler.js:5058
>     mountSuspense runtime-core.esm-bundler.js:1198
>     process runtime-core.esm-bundler.js:1175
>     patch runtime-core.esm-bundler.js:5064
>     componentUpdateFn runtime-core.esm-bundler.js:5607
>     run reactivity.esm-bundler.js:185
>     update runtime-core.esm-bundler.js:5714
>     setupRenderEffect runtime-core.esm-bundler.js:5728
>     mountComponent runtime-core.esm-bundler.js:5510
>     processComponent runtime-core.esm-bundler.js:5468
>     patch runtime-core.esm-bundler.js:5058
>     render2 runtime-core.esm-bundler.js:6229
>     mount runtime-core.esm-bundler.js:4422
>     mount runtime-dom.esm-bundler.js:1606
>     mountStory MountStory.js:47
>     setup MountStory.js:57
>     callWithErrorHandling vue.runtime.esm-bundler.js:1993
>     callWithAsyncErrorHandling vue.runtime.esm-bundler.js:2002
>     __weh vue.runtime.esm-bundler.js:4525
>     flushPostFlushCbs vue.runtime.esm-bundler.js:2196
>     flushJobs vue.runtime.esm-bundler.js:2241
>     promise callback*queueFlush vue.runtime.esm-bundler.js:2123
>     queueJob vue.runtime.esm-bundler.js:2117
>     effect vue.runtime.esm-bundler.js:7530
>     triggerEffect vue.runtime.esm-bundler.js:987
>     triggerEffects vue.runtime.esm-bundler.js:977
> message-compiler.esm-bundler.js:54:18
> ```
> 
> This is how my `plugins/i18n.ts` file looks:
> 
> ```
> import { createI18n } from 'vue-i18n'
> import ro from '~/locales/ro.json'
> 
> export default defineNuxtPlugin(({ vueApp }) => {
>   console.log('here')
>   const i18n = createI18n<[typeof ro], 'ro-RO'>({
>     legacy: false,
>     globalInjection: true,
>     locale: 'ro-RO',
>     messages: {
>       'ro-RO': ro,
>     },
>   })
> 
>   vueApp.use(i18n)
> })
> ```
> 
> It seems like we are never reaching that console log inside the plugin. Would help with this issue however I'm not sure how we can tap into the nuxt plugin loader.

Does both plugins `@histoire/plugin-nuxt` and `@histoire/plugin-vue` are up to date? Latest is 0.10.7

**Comment by danielroe** [comment]
Within `histoire`, there is no runtime Nuxt context. Vue and Nuxt plugins are not run. (Vite plugins will be.) All we do is extract the Vite config from Nuxt; we don't try to mock any more of the Nuxt lifecycle; you would need to do that yourself.

**Comment by Akryum** [comment]
Please create [a discussion](https://github.com/histoire-dev/histoire/discussions) if you need help setting things up. :pray:
