### ISSUE TITLE
Histoire doesn't load components - has `b-vue-router.js?v=0e2740bf:3435 SyntaxError: The requested module '/node_modules/@histoire/app/node_modules/vscode-textmate/release/main.js?v=0e2740bf' does not provide an export named 'INITIAL'`

### ISSUE THREAD

**Issue by sw-yx** [histoire-dev/histoire#285]
### Describe the bug

when i add my first Svelte story, it doesnt load successfully.

![image](https://user-images.githubusercontent.com/6764957/189488547-966a242d-7f33-49fc-8200-47a2598fd247.png)

### Reproduction

my current project with the issue (should be easy to install) is https://github.com/sw-yx/swyxkit/tree/addHistoire

i tried to make a repro locally ([here](https://github.com/sw-yx/repro-histoire-sveltekit-issue))  but it does not have the bug that i found... so i havent been able to isolate what specifically the bug is yet

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.12 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/Library/Caches/fnm_multishells/86443_1662821201246/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/Library/Caches/fnm_multishells/86443_1662821201246/bin/npm
  Browsers:
    Chrome: 105.0.5195.102
    Safari: 15.6.1
  npmPackages:
    @histoire/plugin-svelte: ^0.10.7 => 0.10.7 
    histoire: ^0.10.7 => 0.10.7
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sw-yx** [comment]
oh! thank you guillaume!

**Comment by zubialevich** [comment]
@swyxio  what was it? what was an issue?
