### ISSUE TITLE
_plugin-vue_export-helper.cdc0426e.js not found on gh-pages

### ISSUE THREAD

**Issue by fgravin** [histoire-dev/histoire#292]
### Describe the bug

I can't deploy my `histoire` on `gh-pages`.
Because it tries to load a file `_plugin-vue_export-helper.cdc0426e.js` which can't be read on gh-pages because of the name which starts with a `_`.
The file is present in the `gh-pages` branch.

Related to https://github.com/histoire-dev/histoire/issues/143

- gh-pages branch: https://github.com/camptocamp/rennes3d-front/tree/gh-pages
- code branch: https://github.com/camptocamp/rennes3d-front/tree/ci
- gh-pages: https://camptocamp.github.io/rennes3d-front/#/

Would it be acceptable to remove the underscore from this file ?
Thanks a lot.

### Reproduction

My `histoire.config.ts`

```
import { defineConfig } from 'histoire'
import { HstVue } from '@histoire/plugin-vue'

export default defineConfig({
  setupFile: '/src/histoire-setup.ts',
  plugins: [HstVue()],
  routerMode: 'hash',
  vite: {
    base: process.env.HISTOIRE_BASE || '/dist/',
  },
  tree: {
    groups: [
      {
        id: 'homepage',
        title: 'Homepage', // No toggle
      },
    ],
  },
})
```

### System Info

```shell
System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz
    Memory: 9.72 GB / 30.86 GB
    Container: Yes
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 104.0
  npmPackages:
    @histoire/plugin-vue: ^0.10.7 => 0.10.7 
    @vitejs/plugin-vue: ^3.0.3 => 3.1.0 
    histoire: ^0.10.7 => 0.10.7 
    vite: ^3.0.9 => 3.1.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fgravin** [comment]
I found a work around with https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
Sorry for the noise.

```
- name: .nojekyll
  run: touch .histoire/dist/.nojekyll
```

**Comment by Akryum** [comment]
Yes for most case you need to disable Jekyll on GH Pages.
