### ISSUE TITLE
Uncaught TypeError: DataView is not a constructor

### ISSUE THREAD

**Issue by Qualterink** [histoire-dev/histoire#293]
### Describe the bug

After upgrade vite and histoire into newest version, I have a problem with display stories. 
Npm run build works properly for building library.

### Reproduction

`npm run story:build`

`npm run story:preview`

open browser

![image](https://user-images.githubusercontent.com/21343496/190572369-718b8adb-6f44-4f0c-bd31-b4491b394174.png)

![image](https://user-images.githubusercontent.com/21343496/190572419-a91ee478-d517-4542-8d4f-0f21c9decaf2.png)

histoire.config.ts
```js
import { defineConfig } from "histoire";
import { HstVue } from "@histoire/plugin-vue";

export default defineConfig({
  setupFile: "./src/histoire.setup.ts",
  plugins: [HstVue()],
  tree: {
    groups: [
      {
        title: "Variables",
        id: "Variables"
      },
      {
        title: "Components",
        include: (file) => !file.title.includes("Serialize")
      },
      {
        title: "UI",
        id: "UI"
      }
    ]
  }
});
```

package.json
```js
"vite": "^3.1.1",
"vite-plugin-dts": "^1.5.0",
"@vitejs/plugin-vue": "^3.1.0",
"@histoire/plugin-vue": "^0.10.7",
"histoire": "^0.10.7",
"vue": "^3.2.39"
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 5700U with Radeon Graphics
    Memory: 23.12 GB / 30.70 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 104.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by RafalDrozdz** [comment]
I have the same issue

**Comment by Akryum** [comment]
Please provide a runnable reproduction, thank you! :pray:

**Comment by Qualterink** [comment]
The problem was on our side

**Comment by jyc999** [comment]
hello, it has been solved?
