### ISSUE TITLE
Invalid plugin. src option is required

### ISSUE THREAD

**Issue by adhamfarrag** [histoire-dev/histoire#311]
### Describe the bug

in a Nuxt3 project. Tried adding Histoire and this error is showing up

```

 ERROR  Invalid plugin. src option is required: {"name":"@histoire/plugin-vue","supportPlugin":{"id":"vue3","moduleName":"@histoire/plugin-vue","setupFn":"setupVue3","importStoriesPrepend":"import { defineAsyncComponent as defineAsyncComponentVue3 } from 'vue'"}}

  at normalizePlugin (node_modules/@nuxt/kit/dist/index.mjs:429:11)
  at node_modules/@nuxt/kit/dist/index.mjs:444:61
  at Array.filter (<anonymous>)
  at addPlugin (node_modules/@nuxt/kit/dist/index.mjs:444:47)
  at initNuxt (node_modules/nuxt/dist/index.mjs:1597:5)
  at async loadNuxt (node_modules/nuxt/dist/index.mjs:1635:5)
  at async loadNuxt (node_modules/@nuxt/kit/dist/index.mjs:732:19)
  at async Object.invoke (node_modules/nuxi/dist/chunks/prepare.mjs:30:18)
  at async _main (node_modules/nuxi/dist/cli.mjs:50:20)
```

### Reproduction

https://github.com/adhamfarrag/hello-histoire

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 33.86 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 105.1.43.93
    Chrome: 105.0.5195.125
    Firefox: 105.0.1
    Safari: 16.0
  npmPackages:
    @histoire/plugin-nuxt: ^0.11.0 => 0.11.0 
    @histoire/plugin-vue: ^0.11.0 => 0.11.0 
    histoire: ^0.11.0 => 0.11.0
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
You are putting histoire plugins into Nuxt plugins :sweat_smile:
