### ISSUE TITLE
Uncaught (in promise) TypeError: (void 0) is not a constructor

### ISSUE THREAD

**Issue by llbarr1** [histoire-dev/histoire#320]
### Describe the bug

On Windows 10 the Search doesn't work. When attempting to perform search on dev or prod, the following console error message is reported:

```
SearchPane.bd04cdab.js:218 Uncaught (in promise) TypeError: (void 0) is not a constructor
    at createIndex (SearchPane.bd04cdab.js:218:14)
```

SearchPane.bd04cdab.js:
``` js
 function createIndex() {
      return new (void 0)({
        preset: "match",
        document: {
          id: "id",
          index: [
            "text"
          ]
        },
        worker: true,
        charset,
        language,
        tokenize: "forward"
      });
    }
```

### Reproduction

Either running `story:dev` or running from a production build, search doesn't work.

This behavior was not experienced on MacOS.

### System Info

```shell
Windows 10 Enterprise 21H2
Browsers: 
- Google Chrome Version 105.0.5195.127 (Official Build) (64-bit)
- Microsoft Edge Version 106.0.1370.34 (Official build) (64-bit)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by llbarr1** [comment]
This issue is no longer happening in histoire 0.11.3, however there’s still an issue with search:

#322

**Comment by llbarr1** [comment]
Now that the issue with flexsearch has been temporarily fixed, the issue above continues to exist.

**Comment by Akryum** [comment]
Sorry it hasn't been published just yet 🙇 
![image](https://user-images.githubusercontent.com/2798204/194975079-acc03c5e-e217-43ce-9354-1a54f1e4d764.png)

**Comment by llbarr1** [comment]
Thanks for v.0.11.4 👍🏼 @Akryum
