### ISSUE TITLE
*.story.md is not rendering properly with Sveltekit

### ISSUE THREAD

**Issue by sw-yx** [histoire-dev/histoire#321]
### Describe the bug

was trying out the [docs files](https://github.com/histoire-dev/histoire/issues/237) feature... but add a .story.md file in svelte, and this happens

for component:

![image](https://user-images.githubusercontent.com/6764957/194752656-d45d5a24-ea79-4870-9cd4-92443d8f1582.png)

for "virtual story":

![image](https://user-images.githubusercontent.com/6764957/194752678-97e8138e-1ed5-411d-ac92-4c23c0a6d717.png)

### Reproduction

- PR: https://github.com/sw-yx/swyxkit/pull/113
- Github branch: https://github.com/sw-yx/swyxkit/blob/addHistoire/src/components/Introduction.story.md
- deployed: https://histoire-build-bug-demo.netlify.app/story/src-components-featurecard-story-svelte?variantId=src-components-featurecard-story-svelte-2&tab=docs

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 772.11 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/Library/Caches/fnm_multishells/35700_1665020132817/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.5 - ~/Library/Caches/fnm_multishells/35700_1665020132817/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 15.6.1
  npmPackages:
    @histoire/plugin-svelte: ^0.11.0 => 0.11.0 
    histoire: ^0.11.0 => 0.11.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sw-yx** [comment]
inline docs for svelte would be nice too! happy to brainstorm syntax with you...

**Comment by Akryum** [comment]
Looks like sveltekit applies a transform to markdown files :cat2:

**Comment by Akryum** [comment]
> inline docs for svelte would be nice too! happy to brainstorm syntax with you... i dont think this style of docs will be very discoverable or easy to maintain

AFAIK Svelte doesn't support custom blocks like in Vue:
![image](https://user-images.githubusercontent.com/2798204/194760216-22dd5860-51c3-44a8-962e-2fda182b684b.png)

Maybe we could do something like this:
![image](https://user-images.githubusercontent.com/2798204/194760236-e742371f-911d-4d29-9772-c9009ed1d02f.png)

But then there is no syntax highlighting and we need to be careful about the indentation.

**Comment by Akryum** [comment]
Maybe a comment? 
![image](https://user-images.githubusercontent.com/2798204/194760585-07cf376b-87b2-4979-90f7-0ede47f61378.png)

**Comment by sw-yx** [comment]
wow, if you can parse comments i think that'd  work

but also maybe you just wanna support [mdsvex](https://github.com/pngwn/MDsveX) as your preferred story rendering format instead of .svelte? 

thats what i loved about the old [docz](https://www.docz.site/) style of storybooking, for what its worth. multiple stories, all inline with the description in markdown.

**Comment by Akryum** [comment]
Maybe a markdown file could be compiled on to a story component.
