### ISSUE TITLE
Update from 0.10 to 0.11 causes error with Quasar = TypeError: Cannot read properties of undefined (reading 'prototype')

### ISSUE THREAD

**Issue by rasc-br** [histoire-dev/histoire#323]
### Describe the bug

Version 0.10.x works as expected.
Version 0.11.x throws this error during build and serve: 
```
TypeError: Cannot read properties of undefined (reading 'prototype')
``` 
Since it happens in all story files, I noticed that is related to the configuration where Quasar is included:

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-uaknmn?file=histoire.setup.ts

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 4.19 GB / 15.68 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.37)
    Internet Explorer: 11.0.22000.120
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Try putting your setup file only in the browser:

```js
setupFile: { browser: '...' }
```

**Comment by vsergiu93** [comment]
@rasc-br Have you by chance solved this? I'm currently having the same exact problem.

**Comment by rasc-br** [comment]
@vsergiu93 Unfortunately no, I had to downgrade to 0.10 until Histoire team comes with a solution.

**Comment by Paracelsus-Rose** [comment]
Do you have a working stackblitz for 0.10 with quasar 2?  I generally use quasar-cli but even a pure vite project or anything would be huge.  Really want to get this working, spent the entire night on it to no avail :D

**Comment by rasc-br** [comment]
This is the same thing as before, but on version 0.10.4:
https://stackblitz.com/edit/histoire-vue3-starter-rbqjde?file=package.json
