### ISSUE TITLE
Import error when using vite base path relative

### ISSUE THREAD

**Issue by Florent-Bouisset** [histoire-dev/histoire#326]
### Describe the bug

Hello, thanks for building histoire, love it!

When deploying histoire under a nested public path I set base to empty string
https://vitejs.dev/config/shared-options.html#base

```ts
// histoire.config.ts
export default defineConfig({
  vite: {
    base: "",
  },
```
but some ressources are requesting 
` /story/__sandbox.html` which doesn't exist in my `dist` folder
resulting in this error:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/58945185/195831421-582ed7f8-4537-4391-9b28-45a958079b78.png">

## Workaround

Creating the folder `story` manually and copying in it the content of `assets` fix my issue
```sh
# fix-build.sh
mkdir dist/story &&
cp dist/__sandbox.html dist/story/__sandbox.html &&
cp -R dist/assets dist/story/assets
```

I'm doing that for building:
`npm run build:story && source fix-build.sh
`

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-a7mlkp?file=vite.config.ts

- build and preview the app
- open the base button story

### System Info

```shell
/
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by desprit** [comment]
My `base` is set to an empty string. I'm deploying to GitLab pages where url is of the following structure: `https://deepc.gitlab.io/path/to/project`

Histoire root page opens up correctly but then I have links to each story as the following: `/./story/src-stories-viewer-story-vue` which doesn't correspond to my project url `path/to/project`. If I open a story the url becomes `https://deepc.gitlab.io/story/src-stories-viewer-story-vue` and this is incorrect. Refreshing the page now results in error 404. Any way I can fix that?

**Comment by Akryum** [comment]
Histoire should now follow the `base` from vite configuration. Please reopen if you still have the issue with latest versions of Histoire and Vite.

**Comment by BoredLunatic** [comment]
I came across this error (on v0.17.2) and originally thought it was the base config too. I was able to fix it by updating the `routerMethod` to `hash` in `histoire.config`.

**Comment by mswertz** [comment]
> I came across this error (on v0.17.2) and originally thought it was the base config too. I was able to fix it by updating the `routerMethod` to `hash` in `histoire.config`.

I suppose you mean 'routerMode'

**Comment by BoredLunatic** [comment]
> > I came across this error (on v0.17.2) and originally thought it was the base config too. I was able to fix it by updating the `routerMethod` to `hash` in `histoire.config`.
> 
> I suppose you mean 'routerMode' => that indeed solved it for me thanks!

Apologies it is actually `routerMode` not `routerMethod`.
