### ISSUE TITLE
Display current screen size while resizing (height x width)

### ISSUE THREAD

**Issue by Archetipo95** [histoire-dev/histoire#329]
### Clear and concise description of the problem

Currently when resizing the screen inside a story it's not clear at what resolution the story is rendered.

### Suggested solution

Would be useful to see the current size somewhere, and to see it updating as we resize the story

### Alternative

Actually I don't have an alternative :/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by Akryum** [comment]
You can see the current size (and change it) in the responsive menu:

![image](https://user-images.githubusercontent.com/2798204/196107918-391c3014-bc3c-45cc-9dd5-32422d1c9dae.png)

**Comment by Archetipo95** [comment]
> You can see the current size (and change it) in the responsive menu:
> 
> ![image](https://user-images.githubusercontent.com/2798204/196107918-391c3014-bc3c-45cc-9dd5-32422d1c9dae.png)

Hi thanks for the reply. I know that we can set the screen size, I was just suggesting to show also the current size when we are manuali resizing the story window. Maybe a toast like info or something similar. :)
