### ISSUE TITLE
Box-shadows are being cut off

### ISSUE THREAD

**Issue by nhedger** [histoire-dev/histoire#342]
### Describe the bug

When rendering a component that has a box-shadow, that box-shadow is being cut off.

I was able to reproduce this on the following layouts: `grid`, `single` with or without `iframe`.

In the reproduction, clicking the button will add a "focus-ring", which is a box-shadow. As you'll probably be able to see, the focus-ring is partly cut off.

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-hktpv8?file=src/BaseButton.story.vue

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 974.03 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/Library/Caches/fnm_multishells/16781_1666724779748/bin/node
    Yarn: 1.22.15 - ~/Library/Caches/fnm_multishells/16781_1666724779748/bin/yarn
    npm: 8.5.0 - ~/Library/Caches/fnm_multishells/16781_1666724779748/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 106.0.1
    Firefox Developer Edition: 103.0
    Safari: 16.1
  npmPackages:
    @histoire/plugin-nuxt: ^0.11.5 => 0.11.5 
    @histoire/plugin-vue: ^0.11.5 => 0.11.5 
    histoire: ^0.11.5 => 0.11.5 
    vite: ^3.1.8 => 3.1.8
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
It will be hard to properly handle overflowing content from stories, and a story visual should probably always stay within the preview viewport. I would advise adding a padding so content doesn't overflow.

**Comment by jfitzsimmons2** [comment]
@nhedger I added this to my custom Histoire css so I could see my focus styles/shadows.

```
.histoire-generic-render-story {
    padding: .5rem;
}
```

**Comment by nhedger** [comment]
Thanks, I'll try this.

**Comment by daguitosama** [comment]
# There is not just about shadows

I have noticed there is not just shadows  being cut off, it's the actual component, I have solved the issue with the solution above, but i think will be nice to investigate why is this happening . Look additional captures to see how it behaves with borders and even simple text content. This is the [repo](https://github.com/daguitosama/blog.railab.tech) if some one would like to take a look , can check out the `MainHeadign` story for instance (last capture).

*A component with borders (No historie.css hack)*
<img width="1224" alt="Screen Shot 2022-11-23 at 14 04 44" src="https://user-images.githubusercontent.com/34744883/203628209-0918d849-da60-497d-ac40-765817153f92.png">

*A component with borders (historie.css hack enabled)*
<img width="1224" alt="Screen Shot 2022-11-23 at 14 05 01" src="https://user-images.githubusercontent.com/34744883/203628340-d0412824-253b-4628-9c5f-dc1c13f97491.png">

*A h1 being cutt off*
<img width="1224" alt="Screen Shot 2022-11-23 at 14 11 24" src="https://user-images.githubusercontent.com/34744883/203628835-17921854-1707-41a3-9756-a611948d0331.png">
