### ISSUE TITLE
Svelte component binding gets undefined after using Controls

### ISSUE THREAD

**Issue by bztes** [histoire-dev/histoire#346]
### Describe the bug

When using Histoire Controls every Svelte component binding in the Story gets undefined.

### Reproduction

1. Open https://stackblitz.com/edit/histoire-svelte3-starter-xegtp3?file=src/SvelteBindThis.story.svelte
2. Select Story 'BindThisVsControls'
3. Check 'Disabled' in the Histoire Controls Panel

Result: Value of button gets undefined :(
Expected Result: Button reference should not change

### System Info

```shell
System:
    OS: Linux 6.0 Arch Linux
    CPU: (8) x64 AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
    Memory: 14.62 GB / 31.06 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.11.0 - ~/.nvm/versions/node/v18.11.0/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /.../node_modules/.bin/npm
  Browsers:
    Chromium: 106.0.5249.119
    Firefox: 106.0.1
  npmPackages:
    @histoire/plugin-svelte: ^0.11.5 => 0.11.6 
    histoire: ^0.11.5 => 0.11.6 
    vite: ^3.0.3 => 3.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by TGlide** [comment]
This also happens to me.
