### ISSUE TITLE
Add a drop-down to common responsive width

### ISSUE THREAD

**Issue by hugoattal** [histoire-dev/histoire#37]
I think we should add a drop-down to select common responsive width.

![image](https://user-images.githubusercontent.com/4563971/154727525-6cf36391-98ef-4cc3-8d87-2272901c760a.png)

Suggested width:
- 2560px (4K)
- 1920px (HD)
- 1440px (Laptop L)
- 1024px (Laptop)
- 768px (Tablet)
- 425px (Mobile L)
- 375px (Mobile M)
- 320px (Mobile S)

Config:

```ts
interface Config {
  responsivePresets: ({
    width: number
    label: string
  })[]
}
```

Some ideas for another issue maybe:
- Scale down when provided width is superior to the element actual width
- Provide default width in the story parameter

**Comment by troyere** [comment]
This is not real style value, `width` and `height` should not be typed `number`. Impossible now to choose `px`, `em`, `rem`, and, the most important `%` is impossible too. We can't use `100%` for example. The most important use case.
