### ISSUE TITLE
Fails to resolve aliases within a sveltekit project

### ISSUE THREAD

**Issue by bhvngt** [histoire-dev/histoire#375]
### Describe the bug

When I try to import using aliases, histoire throws following error
```
[plugin:vite:import-analysis] Failed to resolve import "$lib/images/github.svg" from "src/lib/components/button/button.svelte". Does the file exist?
20 |  } from "svelte/internal";
21 |  
22 |  import github from "$lib/images/github.svg"; // this throws error
   |                      ^
23 |  const file = "src/lib/components/button/button.svelte";
24 |
```

It works fine when assets are imported using relative path. It seems to be not picking up the root level `tsconfig.json` 

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-uc6vtd?file=package.json,src%2Flib%2Fcomponents%2Fbutton%2Fbutton.story.svelte,src%2Flib%2Fcomponents%2Fbutton%2Fbutton.svelte&terminal=dev

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/plugin-svelte: ^0.11.7 => 0.11.7 
    histoire: ^0.11.7 => 0.11.7 
    vite: ^3.1.0 => 3.2.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by SzudemJ** [comment]
I can confirm!
@bhvngt maybe passing an alias to vite through your config may help:
```typescript
// histoire.config.ts
import { defineConfig } from 'histoire';
import { HstSvelte } from '@histoire/plugin-svelte';

export default defineConfig({
    plugins: [HstSvelte()],
    setupFile: './histoire.setup.ts',
    vite: {
	resolve: {
	    alias: {
		'$lib': 'src/lib'
	    }
	}
    }
});

```

**Comment by benmccann** [comment]
I hope this will be fixed if we leave SvelteKit's setup plugin in place and remove it's compile plugin. See my comment here: https://github.com/histoire-dev/histoire/pull/393#discussion_r1045263380
