### ISSUE TITLE
LinkError: WebAssembly.instantiate()

### ISSUE THREAD

**Issue by indaco** [histoire-dev/histoire#383]
### Describe the bug

Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #4 module="env" function="setTempRet0" error: function import requires a callable

![histoire-error](https://user-images.githubusercontent.com/13519/205024422-450dca5f-0ff1-4d28-a231-c68b64b402fc.png)

### Reproduction

```bash
npm create svelte@latest histoire-test # skeleton, typescript, eslint, prettier, vitest
cd histoire-test
pnpm i
pnpm i -D histoire @histoire/plugin-svelte
touch histoire.config.ts
mkdir -p src/lib/components/
touch src/lib/components/foo.story.svelte
```

Add the story scripts to `package.json`

```json
"story:dev": "histoire dev",
"story:build": "histoire build",
"story:preview": "histoire preview",
```

Edit `histoire.config.ts` 

```typescript
import { defineConfig } from 'histoire'
import { HstSvelte } from '@histoire/plugin-svelte'

export default defineConfig({
  plugins: [
    HstSvelte(),
  ],
})

```

Edit `src/lib/components/foo.story.svelte`
```typscript
<script lang="ts">
	import type { Hst } from '@histoire/plugin-svelte';
	export let Hst: Hst;
</script>

<Hst.Story>Foo</Hst.Story>
```

run histoire

`pnpm story:dev`

### System Info

```shell
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
    Memory: 4.56 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 3.2.3 - /usr/local/bin/yarn
    npm: 8.18.0 - /usr/local/bin/npm
Browsers:
    Brave Browser: 107.1.45.133
    Chrome: 108.0.5359.71
    Firefox: 107.0
    Safari: 13.1.2
npmPackages:
    @histoire/plugin-svelte: ^0.11.7 => 0.11.7
    histoire: ^0.11.7 => 0.11.7
    vite: ^3.2.4 => 3.2.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Fixed in 2a6350233bd0b6ba47e90bb5f122813f4b5d5a32
