### ISSUE TITLE
External control for dark mode

### ISSUE THREAD

**Issue by mikael-j-rich** [histoire-dev/histoire#388]
### Clear and concise description of the problem

Today the dark mode feature uses useDark from vueuse and this is not configurable externally. 

I would like the possibility to either turn off the dark mode feature or force light mode on initial mount so that the default is always light mode.

Preferably this would be added to config for Histoire.

### Suggested solution

Add dark mode settings in config.theme and use these in the dark util.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by danielduckworth** [comment]
I'm interested in this also. I'm using Vuetify components which has its own way of handling theme switching.  It would be useful if the state could be shared with component framework vendors.
