### ISSUE TITLE
Svelte plugin: incompatibility with svelte-kit starting from 1.0.0-next.574

### ISSUE THREAD

**Issue by vnphanquang** [histoire-dev/histoire#392]
#### Context

There have been 2 recent releases of svelte-kit that causes `histoire` to fail:

1. [1.0.0-next.574](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next574), in which the internal `vite-plugin-svelte-kit` was split into `vite-plugin-sveltekit-build` and `vite-plugin-sveltekit-middleware` [in PR #7990](https://github.com/sveltejs/kit/pull/7990).

2. [1.0.0-next.576](https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next576), in which the `sveltekit` vite plugin became `async` ([PR #7994](https://github.com/sveltejs/kit/pull/7994)).

#### Resolution

For (1), please see this [open PR](https://github.com/histoire-dev/histoire/pull/393) that updates `viteIgnorePlugins`.

For (2), I'm not sure there is a way to get around automatically from `@histoire/plugin-svelte` side; I'm happy to help out further if someone can give me some direction. For now, here is a working workaround for me:

```diff
// vite.config.ts/js

import { sveltekit } from '@sveltejs/kit/vite';
+ import { defineConfig } from 'vite';

/** @type {import('vite').UserConfig} */
+ const config = defineConfig(async () => ({
+       // await for for the new async `sveltekit` here
+	plugins: [await sveltekit()]
+ });

export default config;
```

Maybe if nothing can be done, then this should be added to the documentation somewhere?

### Reproduction

Please run `npm run story:dev` from [this StackBlitz](https://stackblitz.com/edit/sveltejs-kit-template-default-ntonhf?file=package.json&terminal=story:dev). Notice:

- verify that the startup site becomes the `svelte-kit` app instead of `histore`,
- if `svelte-kit` is reverted to `1.0.0-next.573`, everything works as expected.

### System Info

```shell
❯ npx envinfo --system --npmPackages '{histoire,@histoire/*,vite,@vitejs/*}' --binaries --browsers
success Install finished in 1.829s


  System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/controls: 0.11.9 => 0.11.9 
    @histoire/plugin-svelte: 0.11.9 => 0.11.9 
    histoire: 0.11.7 => 0.11.7 
    vite: ^3.2.4 => 3.2.5 

(Ran from the same stackblitz above)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by oneezy** [comment]
have you seen these fixes @bivainis ?
https://github.com/histoire-dev/histoire/pull/393#issuecomment-1351954932
