### ISSUE TITLE
v.0.12.0 breaks on pnm workspace 

### ISSUE THREAD

**Issue by davay42** [histoire-dev/histoire#409]
### Describe the bug

In this pnpm workspace repo https://github.com/DeFUCC/gun-vue I got histoire running in a nested folder for a separate package. Histoire v.0.11.9 is going nice with this setup. But after update to v.0.12.0 I got errors about files not found: histoire doesn't see the images in the public folder inside the nested package, but goes to the top workspace root. JS also gets broken.  May be some configuration may help cope with the change?

`Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@vite/env' imported from [workspace root]/node_modules/.pnpm/vite@4.0.2/node_modules/vite/dist/client/client.mjs`

### Reproduction

Fork https://github.com/DeFUCC/gun-vue and try updating histoire

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 759.41 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.6.0 - /usr/local/bin/node
    npm: 9.2.0 - ~/Library/pnpm/npm
  Browsers:
    Brave Browser: 99.1.36.109
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    vite: ^4.0.2 => 4.0.2
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
I've released a temporary fix on 0.12.2

**Comment by davay42** [comment]
Thank you @Akryum! Yes, this fixes the build! Yet the problem with images in the public folder is still to be solved. No rush, can move the images to workspace root till then.

```
Histoire config: theme.logo.square file /gun-vue-logo.svg does not exist (resolved to /gun-vue-logo.svg), check for typos in the paths
Histoire config: theme.logo.light file /components.svg does not exist (resolved to /components.svg), check for typos in the paths
Histoire config: theme.logo.dark file /components.svg does not exist (resolved to /components.svg), check for typos in the paths
```

**Comment by Akryum** [comment]
This is a warning that you can ignore, I'll improve it to also check for the public folder

**Comment by alvarosabu** [comment]
@davay42 were you able to build it and deploy it? 

I'm having an error running `build`, I'm using unocss, dunno if it's related

```
vite v4.0.3 building for development...

watching for file changes...
file:///Users/x400048/Projects/github/portfolio/packages/ui/node_modules/histoire/dist/node/build.js:129
    const styleOutput = result.output.find(o => o.name === 'style.css' && o.type === 'asset');
                                      ^

TypeError: Cannot read properties of undefined (reading 'find')
```

**Comment by davay42** [comment]
@alvarosabu yes, builds go fine now!
