### ISSUE TITLE
Histoire 0.12.4 not working with vite 4.1

### ISSUE THREAD

**Issue by jbreuil** [histoire-dev/histoire#434]
### Describe the bug

TypeError: Cannot read properties of null (reading 'isCE')

When using a simple example of histoire with latest version of histoire and vite, stories are unabled to being listed, it's seems to be related to histoire using a duplicate instance of vue.

### Reproduction

[stack blitz](https://stackblitz.com/edit/histoire-vue3-starter-pdbnyn?file=package.json)

Forked from the histoire documentation example with bumped version.

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/plugin-vue: ^0.12.4 => 0.12.4 
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    histoire: ^0.12.4 => 0.12.4 
    vite: ^4.1.1 => 4.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hmt** [comment]
To be precise, it is 4.1 not 4.0.

**Comment by yshrsmz** [comment]
Had the same issue today.
vite v4.1 came from Nuxt v3.1.2

**Comment by Akryum** [comment]
Hello, we are aware of this issue and trying to fix it asap
