### ISSUE TITLE
Tailwind with DaisyUI not loaded correctly

### ISSUE THREAD

**Issue by ngoldack** [histoire-dev/histoire#435]
### Describe the bug

Hi, thanks for your amazing work with this!

I'm having a problem with loading Tailwind  [DaisyUI](https://github.com/saadeghi/daisyui) correctly.
Maybe its just a config error. See stackblitz for my setup.

### Reproduction

https://stackblitz.com/edit/histoire-svelte3-starter-bmkhk8?file=src/Test.svelte

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
    Memory: 31.15 GB / 63.67 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.2.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.95)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @histoire/plugin-svelte: ^0.13.0 => 0.13.0
    histoire: ^0.13.0 => 0.13.0
    vite: ^4.1.1 => 4.1.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
Your reproduction is missing some configuration to include tailwindcss in the CSS of the app:
https://stackblitz.com/edit/histoire-svelte3-starter-bj2ryh?file=src%2Fhistoire-setup.ts,vite.config.ts,postcss.config.js
