### ISSUE TITLE
0.13.1 started throwing during build

### ISSUE THREAD

**Issue by hmt** [histoire-dev/histoire#440]
### Describe the bug

This message comes up when building:

```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default ESM loader. Received protocol 'virtual:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:964:11)
    at defaultResolve (node:internal/modules/esm/resolve:1040:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:416:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36)
```

### Reproduction

Sorry, don't have a minimal repo at hand.

Checkout shallow from `https://github.com/SVWS-NRW/SVWS-Server/tree/dev/svws-webclient` and run `npm i` in that dir then proceed to `https://github.com/SVWS-NRW/SVWS-Server/tree/dev/svws-webclient/src/ui-components/ts` to `npm run story:build`

### System Info

```shell
System:
    OS: macOS 13.2
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 33.87 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.6.0 - /usr/local/bin/node
    npm: 9.4.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 109.0.5414.119
    Firefox: 109.0.1
    Safari: 16.3
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by FliPPeDround** [comment]
I have the same problem, is there a solution now?
