### ISSUE TITLE
sandboxDarkClass is not toggled with storeColorScheme: false

### ISSUE THREAD

**Issue by valgeirb** [histoire-dev/histoire#444]
### Describe the bug

Setting 

```
{
  defaultColorScheme: 'light',
  storeColorScheme: false,
}
```

results in `sandboxDarkClass` not being set when toggling dark mode.

 

### Reproduction

I think I provided enough information.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 2.16 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.volta/tools/image/node/16.14.2/bin/node
    Yarn: 1.22.18 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
    npm: 8.5.0 - ~/.volta/tools/image/node/16.14.2/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @histoire/plugin-vue: ^0.13.2 => 0.13.2 
    @vitejs/plugin-vue: ^4.0.0 => 4.0.0 
    histoire: ^0.13.2 => 0.13.2 
    vite: ^4.0.4 => 4.0.4
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
I think it's caused by `storeColorScheme: false`
