### ISSUE TITLE
TypeScript definitions for Svelte components

### ISSUE THREAD

**Issue by jeremyjacob** [histoire-dev/histoire#450]
### Clear and concise description of the problem

Currently, *.svelte.story components get their boilerplate components from the `Hst` prop which much be typed as `any `when using TypeScript.

### Suggested solution

Export optional types for use with the Hst prop from `@histoire/plugin-svelte`.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that requests the same feature to avoid creating a duplicate.

**Comment by hkievet** [comment]
You can do this:

```
<!-- Meow.story.svelte -->
<script lang="ts">
	import type { Hst } from '@histoire/plugin-svelte/src/helpers';
	export let Hst: Hst;
</script>

<Hst.Story>🐱</Hst.Story>

```

<img width="632" alt="image" src="https://github.com/histoire-dev/histoire/assets/6579980/f8fe3fe0-0a1d-46d7-96b3-35bd5dfa02e8">

**Comment by Akryum** [comment]
See https://histoire.dev/guide/svelte3/stories.html#typescript
