### ISSUE TITLE
Latest releases of Histoire and Nuxt are not compatible

### ISSUE THREAD

**Issue by clemcode** [histoire-dev/histoire#472]
### Describe the bug

Versions:
histoire, @histoire/plugin-nuxt, @histoire/plugin-vue : 0.15.8
nuxt: 3.2.3

Hi!

When running `story:dev` with the latest releases of Histoire and Nuxt, an Iframe containing the rendered `app.vue` file gets displayed below the actual story (See image below). If you scroll down the page on the repro, you will notice that the same page is also displayed below the viewport. 

A few errors are also thrown at startup, but don't seem to prevent the app from running.

```
Sourcemap for "/__resolved__virtual:$histoire-theme.css" points to missing source files
stories/test.story.vue 4302ms (setup:31ms, execute:3183ms, run:1088ms)
[nuxt] error caught during app initialization ReferenceError: document is not defined
    at normalizeContainer (file:///home/projects/nuxt-starter-7hjhxl/node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1616:21)
    at app.mount (file:///home/projects/nuxt-starter-7hjhxl/node_modules/@vue/runtime-dom/dist/runtime-dom.cjs.js:1537:27)
    at initApp (file:///home/projects/nuxt-starter-7hjhxl/node_modules/nuxt/dist/app/entry.mjs:55:14)
Collect stories end 17800ms
Collect stories start all
stories/test.story.vue 96ms (setup:57ms, execute:1ms, run:38ms)
Collect stories end 108ms
```

<img width="1432" alt="" src="https://user-images.githubusercontent.com/1439623/222900128-8f05b72f-77a1-4258-8003-1be71c48e3ae.png">

Thanks for this awesome project, can't wait to use it with Nuxt!

### Reproduction

https://stackblitz.com/edit/nuxt-starter-7hjhxl

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @histoire/plugin-nuxt: ^0.15.8 => 0.15.8 
    @histoire/plugin-vue: ^0.15.8 => 0.15.8 
    histoire: ^0.15.8 => 0.15.8
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by medfreeman** [comment]
Additional reproduction here: https://stackblitz.com/edit/histoire-nuxt3-starter-eb2jnf
(This is the same stackblitz i proposed in #471)

I also reproduced it locally by cloning this repo and making the appropriate updates (instead of displaying the demo page it also displays what's inside the `app.vue` template, being `hi there` in the local nuxt example).

Note: if adding `pages` templates you would get 404s because of nuxt's `vue-router` errors not recognising `histoire` routes.
