### ISSUE TITLE
TypeError: Unknown file extension ".ts" for "[...]/app.config.ts" in Nuxt

### ISSUE THREAD

**Issue by medfreeman** [histoire-dev/histoire#475]
### Describe the bug

In nuxt, when an `app.config.ts` file is present, the following error is displayed when building histoire:

output from stackblitz:
```shell
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "TypeError: Unknown file extension ".ts" for /home/projects/histoire-nuxt3-starter-eb2jnf-keeeav/app.config.ts".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

The corresponding import happens in `.nuxt/app.config.mjs` when an `app.config.ts` file is present in `nuxt` folder, but only inlines `nuxt.config.ts` `appConfig` object value when this file is not present.

When running `histoire dev`, the app renders but shows no story since this error prevents each story from building properly.

### Reproduction

https://stackblitz.com/edit/histoire-nuxt3-starter-eb2jnf-keeeav

Note : stackblitz `startCommand` has been set to `npm run story:build` so the error is not swallowed.

I also confirmed the bug locally.

Alternative: in the meantime one can use the `appConfig` key in `nuxt.config.ts` instead.

### System Info

```shell
System:
  OS: Linux 5.15 Arch Linux
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
  Memory: 11.10 GB / 13.65 GB
  Container: Yes
  Shell: 5.9 - /usr/bin/zsh
Binaries:
  Node: 18.12.1 - /run/user/1000/fnm_multishells/423_1678100398210/bin/node
  npm: 8.19.2 - /run/user/1000/fnm_multishells/423_1678100398210/bin/npm
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by marshallswain** [comment]
I'm running into this same issue.  I'm currently working around it by locking the nuxt plugin to the previous minor release. This appears to break hot module reloading, but it's better than not working at all.

```
"@histoire/plugin-nuxt": "^0.14.2",
```

@medfreeman could you give an example of using the `appConfig` key in `nuxt.config.ts`?

**Comment by medfreeman** [comment]
Sure: https://nuxt.com/docs/api/configuration/nuxt-config#appconfig
You would basically put the configuration object you currently provide in 'app.config.ts' under the 'appConfig' key in 'nuxt.config.ts' instead, that's all.

**Comment by mashuble** [comment]
Same issue for me

**Comment by medfreeman** [comment]
Has been fixed in the meantime!
https://stackblitz.com/edit/histoire-nuxt3-starter-eb2jnf-juxd4r
