### ISSUE TITLE
Default Tailwind colors persist and hinder accessibility of custom colors in Histoire Design System

### ISSUE THREAD

**Issue by samuveth** [histoire-dev/histoire#507]
### Describe the bug

The Histoire package has an issue with the Tailwind Design System feature where the default Tailwind colors continue to appear in the border and text color tabs, even after adding a custom colors object directly to the theme object in tailwind.config. This is not the expected behavior, as the custom colors object should override the default Tailwind colors, preventing them from being used and displayed.

Moreover, this issue is particularly annoying because it forces users to scroll down through the default colors to access their custom-defined colors.

### Reproduction

1. Create a new project with the Histoire package.
2. Configure tailwind.config.js by adding a custom colors object to the theme object.
3. Run the project and navigate to the Histoire Tailwind Design System interface.
4. Observe that the default Tailwind colors are still displayed in the border and text color tabs, despite the custom colors object in the configuration.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 73.78 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@16/bin/npm
    Watchman: 2023.02.20.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 111.1.49.132
    Chrome: 111.0.5563.146
    Chrome Canary: 114.0.5685.0
    Firefox: 101.0
    Safari: 16.3
  npmPackages:
    @histoire/plugin-vue: ^0.15.8 => 0.15.8 
    @vitejs/plugin-vue: ^4.1.0 => 4.1.0 
    histoire: ^0.15.9 => 0.15.9 
    vite: ^4.2.0 => 4.2.1
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by etiennelenhart** [comment]
Getting the same behavior. But for me I think it basically shows all of Tailwind's default colors on every section related to colors (background, text, border).
I'm using the following _tailwind.config.ts_ in a SvelteKit project:
```typescript
import type { Config } from 'tailwindcss'
import colors from 'tailwindcss/colors'

export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      cyan: colors.cyan,
      yellow: colors.yellow,
      red: colors.red,
      slate: colors.slate,
      black: colors.black,
      white: colors.white,
    },
    extend: {},
  },
} satisfies Config
```

**Comment by zweeen** [comment]
Hey guys 🙂 

Thanks for this amazing tool.
I have the same problem as @samuveth, default Histoire Tailwind config persist despit setting Tailwind with my own config.

Any update on this ?

**Comment by samuveth** [comment]
It's working with latest version for me when adding the colors to the theme directly and not to extend.
