### ISSUE TITLE
At least one <template> or <script> is required in a single file component

### ISSUE THREAD

**Issue by Javid-Izadfar** [histoire-dev/histoire#527]
### Describe the bug

I'm receiving  `At least one <template> or <script> is required in a single file component` for every `.story.vue` file I've got on a Nuxt3 (`@3.3.2` and `@3.4.3`) project.

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-wlv4el?file=package.json

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 3.70 GB / 7.72 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v18.15.0/bin/npm
  npmPackages:
    @histoire/plugin-nuxt: 0.16.1 => 0.16.1 
    @histoire/plugin-vue: 0.16.1 => 0.16.1 
    histoire: 0.16.1 => 0.16.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by danlourenco** [comment]
Getting the same thing.

**Comment by samplep182** [comment]
Facing same issue on MacOS using pnpm.

**Comment by romainl** [comment]
FWIW, removing any reference to `@histoire/plugin-nuxt` from `histoire.config.ts` made the error disappear:

    import { defineConfig } from "histoire";
    import { HstVue } from "@histoire/plugin-vue";
    // import { HstNuxt } from "@histoire/plugin-nuxt";

    export default defineConfig({
      plugins: [
        HstVue(),
        // HstNuxt()
      ],
    });

which is rather surprising since the stack trace doesn't mention `plugin-nuxt` at all:

```
Error while collecting story /Users/username/project/components/Meow.story.vue:
SyntaxError: At least one <template> or <script> is required in a single file component.
    at Object.parse$4 [as parse] (/Users/username/project/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:5269:21)
    at createDescriptor (/Users/username/project/node_modules/@vitejs/plugin-vue/dist/index.cjs:74:43)
    at transformMain (/Users/username/project/node_modules/@vitejs/plugin-vue/dist/index.cjs:2277:34)
    at TransformContext.transform (/Users/username/project/node_modules/@vitejs/plugin-vue/dist/index.cjs:2798:16)
    at Object.transform (file:///Users/username/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:42883:44)
    at async loadAndTransform (file:///Users/username/project/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:53349:29)
```

---

No Storybook, no Histoire… The "stories" situation is not very good at the moment for Nuxt 3 users.

**Comment by DanielleConstell** [comment]
Also having this issue with a complete clean nuxt install and these packages;
    "@histoire/plugin-nuxt": "^0.16.1",
    "@histoire/plugin-vue": "^0.16.1",
    "histoire": "^0.16.1",
    "nuxt": "^3.5.1",

**Comment by awacode21** [comment]
i am currently migrating my vue project to a nuxt project. But i also get this issue with histoire which makes it impossible to use histoire with nuxt3. Any idea or workaround?

**Comment by romainl** [comment]
@awacode21 our current workaround is to keep Nuxt out of our components as much as possible. It sort of gives us the benefits of agnosticism (for some meaning of agnosticism), but Nuxt's auto-imports and all are hard to let go :-(.

**Comment by ramonakira** [comment]
I am also experiencing this issue.

**Comment by t0byman** [comment]
I am also experiencing this issue.

**Comment by fingm-t** [comment]
I am also experiencing this issue.

**Comment by romainl** [comment]
Upgrading to "@histoire/plugin-nuxt" to 0.16.2 somewhat made the error and stack trace go away, but there is still no Nuxt autoloading or other Nuxt-provided features.

**Comment by ianjamieson** [comment]
I am getting this error when using histoire with a nuxt module that I am creating.

In my module configuration I have this to import the components:

```
  hooks: {
    'components:dirs'(dirs) {
      dirs.push({
        path: fileURLToPath(new URL('./runtime/components', import.meta.url)),
        prefix: 'Tx',
      });
    },
    'imports:dirs'(dirs) {
      dirs.push(fileURLToPath(new URL('./runtime/composables', import.meta.url)));
      dirs.push(fileURLToPath(new URL('./runtime/enums', import.meta.url)));
    },
  },
```

Which works ok, but when I add the `global: true` option (so I can auto import components with the `:is` directive), like this:

```
  hooks: {
    'components:dirs'(dirs) {
      dirs.push({
        path: fileURLToPath(new URL('./runtime/components', import.meta.url)),
        prefix: 'Tx',
       global: true
      });
    }
  },
```

This is when I get the error mentioned above.

**Comment by cutugno01** [comment]
> I managed to get passed this issue by editing `@historie/plugin-nuxt/dist/index.js` and resolving with the vuePlugins but not updating the config object.
> 
> ```
> nuxt.hook('vite:extendConfig', (config, { isClient }) => {
>                     // @ts-ignore
>                     if (isClient) {
>                       const plugins = []  // <-----------
>                         for (const name in vuePlugins) {
>                             if (!config.plugins?.some(p => p?.name === name)) {
>                                 const [plugin, key] = vuePlugins[name];
>                                 // @ts-ignore
>                                 // config.plugins.push(plugin(config[key]));
>                                 plugins.push(plugin(config[key]));  // <-----------
>                             }
>                         }
> 
>                         resolve({
>                           ...config,
>                           plugins: [  // <-----------
>                             ...config.plugins,  // <-----------
>                             ...plugins,  // <-----------
>                           ],  // <-----------
>                         });
>                     }
>                 });
> ```
> 
> This stopped the files from compiling twice, although i still have the same issue when using for example `nuxt-icon` package.

This seems to be working for me.
It is also solving an error in `@nuxt/devtools/dist/runitme/plugins/view/Main.vue` indicating to `import type { CSSProperties } from 'vue'`

**Comment by samuveth** [comment]
I'm still getting this error for 'nuxt-icon' and 'nuxt-icons' plugins.

```
[vite:vue] At least one <template> or <script> is required in a single file component.
file: /Users/sam/dev/clones/nuxt-tune/node_modules/nuxt-icon/dist/runtime/Icon.vue?nuxt_component=async
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

SyntaxError: At least one <template> or <script> is required in a single file component.
    at Object.parse$2 [as parse] (/Users/sam/dev/clones/nuxt-tune/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:1275:7)
    at createDescriptor (/Users/sam/dev/clones/nuxt-tune/node_modules/@vitejs/plugin-vue/dist/index.cjs:84:43)
    at transformMain (/Users/sam/dev/clones/nuxt-tune/node_modules/@vitejs/plugin-vue/dist/index.cjs:2282:34)
    at Object.transform (/Users/sam/dev/clones/nuxt-tune/node_modules/@vitejs/plugin-vue/dist/index.cjs:2814:16)
    at /Users/sam/dev/clones/nuxt-tune/node_modules/vite-plugin-inspect/dist/index.cjs:932:28
    at Object.plugin2.<computed> (/Users/sam/dev/clones/nuxt-tune/node_modules/vite-plugin-inspect/dist/index.cjs:919:16)
    at file:///Users/sam/dev/clones/nuxt-tune/node_modules/rollup/dist/es/shared/node-entry.js:25518:40 {
  id: '/Users/sam/dev/clones/nuxt-tune/node_modules/nuxt-icon/dist/runtime/Icon.vue?nuxt_component=async',
  plugin: 'vite:vue',
  name: 'RollupError',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  watchFiles: [
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/bundle-main.js',
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/bundle-sandbox.js',
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/bundled/sandbox.js',
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/app/style/sandbox.css',
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/bundled/index.js',
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/style.css',
    '/Users/sam/dev/clones/nuxt-tune/node_modules/@histoire/app/dist/bundled/style.css',
    
    ```
