### ISSUE TITLE
After upgrading nuxt v3.7.0, I get "TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#app"

### ISSUE THREAD

**Issue by zweeen** [histoire-dev/histoire#587]
### Describe the bug

After upgrading Nuxt to v3.7.0, I get  this error :

```
Error while collecting story /Users/toto/Sites/front-v2/stories/BaseChip.story.vue:
TypeError [ERR_PACKAGE_IMPORT_NOT_DEFINED]: Package import specifier "#app" is not defined in package /Users/toto/Sites/front-v2/package.json imported from /Users/toto/Sites/front-v2/.nuxt/app.config.mjs
    at new NodeError (node:internal/errors:405:5)
    at importNotDefined (node:internal/modules/esm/resolve:348:10)
    at packageImportsResolve (node:internal/modules/esm/resolve:775:9)
    at moduleResolve (node:internal/modules/esm/resolve:930:16)
    at defaultResolve (node:internal/modules/esm/resolve:1129:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
```

- histoire: 0.17.0
- histoire/plugin-nuxt: 0.17.0
- histoire/plugin-vue: 0.17.1

### Reproduction

I tried to reproduce the error just with the package listed above: https://stackblitz.com/edit/histoire-nuxt3-starter-ib4h3i?file=package.json,nuxt.config.ts.

But it seems that I can't reproduce the error. I Think that I have another package installed that make this error appears.
Here this is my package.json:

```
{
    "name": "nuxt-app",
    "private": true,
    "scripts": {
        "story:dev": "histoire dev",
        "story:build": "histoire build",
        "story:preview": "histoire preview --port 4567",
        "build": "nuxt build",
        "dev": "nuxt dev",
        "generate": "nuxt generate",
        "preview": "nuxt preview",
        "postinstall": "nuxt prepare"
    },
    "devDependencies": {
        "@histoire/plugin-nuxt": "^0.17.0",
        "@histoire/plugin-vue": "^0.17.1",
        "@nuxt/devtools": "latest",
        "@nuxtjs/eslint-config-typescript": "^12.0.0",
        "@nuxtjs/eslint-module": "^4.1.0",
        "@nuxtjs/tailwindcss": "^6.8.0",
        "@types/node": "^18.16.19",
        "@vue/eslint-config-airbnb-with-typescript": "^7.0.0",
        "@vueuse/core": "^10.2.1",
        "@vueuse/nuxt": "^10.2.1",
        "autoprefixer": "^10.4.14",
        "eslint": "^8.44.0",
        "eslint-config-airbnb": "^19.0.4",
        "eslint-config-prettier": "^8.8.0",
        "eslint-import-resolver-typescript": "^3.5.5",
        "eslint-plugin-import": "^2.27.5",
        "eslint-plugin-prettier": "^5.0.0",
        "eslint-plugin-vue": "^9.15.1",
        "histoire": "^0.17.0",
        "nuxt": "^3.7.0",
        "nuxt-svgo": "^3.4.0",
        "nuxt-viewport": "^2.0.6",
        "postcss": "^8.4.27",
        "prettier": "^3.0.2",
        "prettier-plugin-tailwindcss": "^0.5.3",
        "sass": "^1.64.1"
    },
    "dependencies": {
        "@pinia/nuxt": "^0.4.11",
        "pinia": "^2.1.4",
        "vue-final-modal": "^4.4.5"
    },
    "overrides": {
        "vue": "latest"
    }
}
```

Thanks for your help :)

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 675.04 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.0/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.110
    Safari: 16.6
  npmPackages:
    @histoire/plugin-nuxt: ^0.17.0 => 0.17.0 
    @histoire/plugin-vue: ^0.17.1 => 0.17.1 
    histoire: ^0.17.0 => 0.17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ahmed7am1d** [comment]
Getting the same error !!! I just started a NuxtJs project with UnoCss, and I am getting the same error when I remove the package everything is fine !!

**Comment by positiveprogrammer** [comment]
It looks devtools conflict with story collection process.

**Comment by cutugno01** [comment]
Downgrading to nuxt 3.6.5 solves the issue
`npm i nuxt@3.6.5`

**Comment by zola33dsf** [comment]
Any updates ?

**Comment by HybridEyeGrillage** [comment]
> It looks devtools conflict with story collection process.

If this is the case, is there any way to avoid using Nuxt DevTools with Histoire? Maybe through the process.env.HISTOIRE_DEV environment variable?

**Comment by MilanFox** [comment]
Am able to reproduce the Error, here is a minimal reproduction:

https://stackblitz.com/edit/nuxt-starter-dytmd1?file=package.json
Start Histoire with "histoire dev" to produce the error.

@Akryum Do you have any idea?

**Comment by marshallswain** [comment]
In that reproduction, update nuxt.config.ts to the following and Histoire works:

```ts
// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  devtools: false,
});
```

![Screenshot 2023-10-05 at 9 04 01 PM](https://github.com/histoire-dev/histoire/assets/128857/20d2890e-56ab-40cd-9372-f16fb2aa98cf)

**Comment by fallsimply** [comment]
@marshallswain The issue was with any Nuxt Module not just devtools. v0.17.2 should've fixed the issue.

**Comment by Akryum** [comment]
Looks like using latest versions of nuxt and histoire packages the issue is fixed: https://stackblitz.com/edit/nuxt-starter-vybmmd?file=package.json
