### ISSUE TITLE
Any story using useFetch fails

### ISSUE THREAD

**Issue by ssotomayor** [histoire-dev/histoire#591]
### Describe the bug

`useFetch` seems to work fine in the Nuxt context but not within the stories, i tried to console.log what is useFetch returning and it seems that within Histoire it returns an html injecting some vite client:

_Output from console.log(useFetch) within Histoire_
```
<!DOCTYPE html> <html> <head> <script type="module" src="/@vite/client"></script> <title></title> <link rel="icon" href=""/> <meta charset="utf-8"> <meta name="viewport" content="width=device-width,initial-scale=1"> <meta name="description" content=""> </head> <body> <div id="app"></div> <script type="module" src="/@fs/Users/sanden/Projects/games-app-react/node_modules/@histoire/app/dist/bundle-main.js"></script> </body> </html> function useFetch(request, arg1, arg2) 
...
```

### Reproduction

Any story that uses useFetch

### System Info

```shell
System:
    OS: macOS 13.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.96 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.6.12 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Brave Browser: 116.1.57.62
    Chrome: 116.0.5845.187
    Safari: 16.6
  npmPackages:
    @histoire/plugin-nuxt: ^0.17.0 => 0.17.0
    @histoire/plugin-vue: ^0.17.0 => 0.17.1
    histoire: ^0.17.0 => 0.17.0
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ssotomayor** [comment]
Actually it looks like since i'm doing `useFetch('/api/someApiEndpointFromNuxt')` it doesn't work since Histoire does not start the endpoints in /api from Nuxt.

**Comment by ssotomayor** [comment]
So i've found a workaround this, which is not that hacky, basically you can start Nuxt 3 server running `nuxi dev` or basically `./node_modules/nuxi/bin/nuxi.mjs dev` and then start histoire at the same time with `histoire dev`:

So first in scripts for _package.json_ i've added:

```json
"scripts": {
  "story:dev": "./node_modules/nuxi/bin/nuxi.mjs dev & histoire dev",
}
```
To run both in parallel, then on _histoire.config.ts_ i've changed the vite server to add a proxy to /api (assuming i'm running Nuxt on port 3000 and Histoire on 6006:

_histoire.config.ts_
```typescript
import { defineConfig } from "histoire";
import { HstVue } from "@histoire/plugin-vue";
import { HstNuxt } from "@histoire/plugin-nuxt";

export default defineConfig({
  setupFile: "./histoire.setup.ts",
  plugins: [HstVue(), HstNuxt()],
  vite: {
    server: {
      proxy: {
        "/api": {
          target: "http://localhost:3000/api",
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
        },
      },
    },
  },
  ```
  
  Now the story will be able to fetch the data from Nuxt's server, having the url in the story as:
  
  ```vue
<script lang="ts" setup>
import { useMq } from "vue3-mq";

const mq = useMq();
const { data } = useFetch('/api/getData'); // fetching from Nuxt server as vite will redirect /api to http://localhost:3000 !
</script>
<template>
    <div></div>
</template>
  ```
  
  Now starting up with `npm run story:dev` will run both and components that fetch data work.

**Comment by Akryum** [comment]
I would recommend mocking the network with something like msw.

**Comment by ssotomayor** [comment]
> I would recommend mocking the network with something like msw.

I ended up using [MirageJS](https://miragejs.com/) as i ran into [a couple of issues with MSW](https://github.com/mswjs/msw/issues/1539#issuecomment-1589401153) at the moment.

Was able to mock translations as well, great idea @Akryum !

Posting my _histoire.setup.ts_ here if it's helpful to someone.

This is on Nuxt 3.6.5, there seem to be issues with 3.7.0 atm.

https://github.com/histoire-dev/histoire/issues/587

```typescript
// src/histoire.setup.ts

import { Vue3Mq, MqResponsive } from "vue3-mq";
import { defineSetupVue3 } from "@histoire/plugin-vue";
import { createServer } from "miragejs";
import { createI18n } from "vue-i18n";
import { transformedArray } from "./utils/utils";
import mockTranslationsEn from "./stories/apiMocks/mockTranslationsEn.json";
import mockBuyBitcoinBanner from "./stories/apiMocks/mockBuyBitcoinBanner.json";

createServer({
  routes() {
    this.get("/api/getTranslations", () => []);
    this.get("/api/buybanner", () => mockBuyBanner);
    this.get(
      "https://cdn.jsdelivr.net/npm/shiki-es@0.2.0/dist/assets/dist/onig.wasm"
    );
    this.passthrough("https://cdn.jsdelivr.net/**");
  },
});

const i18n = createI18n({
  legacy: false,
  messages: {
    "en-US": transformedArray(mockTranslationsEn.data),
  },
});

export const setupVue3 = defineSetupVue3(({ app, story, variant }) => {
  app
    .use(Vue3Mq, {
      defaultBreakpoint: "xxl",
      breakpoints: {
        xs: 0,
        sm: 480,
        md: 768,
        lg: 1024,
        xl: 1440,
        xxl: 1600,
      },
    })
    .use(i18n)
    .component("mq-responsive", MqResponsive);
});
```

**Comment by ssotomayor** [comment]
For now i've resolved this with MirageJS

**Comment by jackchoumine** [comment]
> I would recommend mocking the network with something like msw.

Hello, I am using msw in histore, like this:

```js
import { defineSetupVue3 } from '@histoire/plugin-vue'

import { worker } from './mocks/browser'

export const setupVue3 = defineSetupVue3(({ app, story, variant }) => {
 // msw is ready ,then set provide but child Component can not get tableFetch
  setupWorker().then(() => {
    app.provide('tableFetch', tableFetch)
    app.use(ElementPlus)
  })
})

function tableFetch(url, params) {
  const searchStr = new URLSearchParams(params)
  let _url = url
  if (searchStr) {
    _url += '?' + searchStr
  }
  return fetch(_url, {
    method: 'get',
    headers: {
      'content-type': 'application/json',
    },
  }).then(res => res.json())
}

function setupWorker() {
  return worker.start()
}
```

child component can not get tableFetch .

How can I fix it. I dont find any tips in histoire docs.
