### ISSUE TITLE
Plugins/Addons

### ISSUE THREAD

**Issue by hugoattal** [histoire-dev/histoire#61]
I think it would be a cool idea to provide APIs to create addons.

Example of APIs :
- Provide App, Story and Variant access (Already covered with `defineVue3StorySetup`)
- Inject script to app
- Inject script to stories
- Add icon to story top bar
- Add icon to explorer top bar
- Add tab to Controls/Doc panel
- Add panels

Then have a process of installing some addons.
Probably something like this in the setup script

```ts
import myCoolAddon from 'myCoolAddon'
import { installAddon } from 'histoire/client'

installAddon(myCoolAddon, { myConfigParam: true })
```

or directly in the config file

```ts
export default defineConfig({ 
  addons: [
    { package: 'myCoolAddon', config: { myConfigParam: true } }
  ]
})
```

**Comment by Akryum** [comment]
I'm closing as the Plugin API bases are already available. We now need to discuss expanding and documenting it.
See https://github.com/histoire-dev/histoire/discussions/240
