### ISSUE TITLE
missing npm package for 0.17.3

### ISSUE THREAD

**Issue by minddust** [histoire-dev/histoire#610]
### Describe the bug

guess it was never published?

### Reproduction

check: https://www.npmjs.com/package/histoire

### System Info

```shell
firefox
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Akryum** [comment]
0.17.3 only had changes in [@histoire/plugin-nuxt](https://www.npmjs.com/package/@histoire/plugin-nuxt).
