### ISSUE TITLE
Vite's base option breaks asset paths

### ISSUE THREAD

**Issue by VanishMax** [histoire-dev/histoire#635]
### Describe the bug

I wanted to host Histoire in the sub directory of my main Vue application. For this purpose, I changed the `base` property for Histoire build in the `vite.config.ts` file like so:

```ts
import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';

export default defineConfig({
  plugins: [vue()],
  base: process.env.HISTOIRE ? '/histoire' : '',
});
```

When I tried to run `pnpm story:dev`, Histoire UI successfully loaded. Yet, when I opened a story, it didn't show up on the screen. Found these logs in the console:

```
GET http://localhost:3000/histoire__sandbox.html?storyId=src-basebutton-story-vue&variantId=_default 404 (Not Found)
```

Interestingly, `pnpm story:build` command produces `index.html` and a `__sandbox.html` but Vite (or Histoire) tries to prefix it with the `histoire` string. 

This could actually be not a bug but a feature. For example, [Vitepress exports base option](https://vitepress.dev/guide/deploy#setting-a-public-base-path) in their own config. So, it could be solved by either adding base into the histoire's config or relying on the Vite's one.

This bug prohibits me to put Histoire into the sub-directory and run it alongside the main Vue application.

### Reproduction

https://stackblitz.com/edit/histoire-vue3-starter-base-bug

In the repro, I added a single line in the `vite.config.ts` file in comparison to the Histoire's template on Stackblitz. When you open, it will run immediately. Try opening any story – it shows empty screen and puts an error into the console.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 62.88 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.7.6 - /usr/local/bin/pnpm
  Browsers:
    Chrome: 119.0.6045.123
    Safari: 17.0
  npmPackages:
    @histoire/plugin-vue: ^0.17.5 => 0.17.5 
    @vitejs/plugin-vue: ^4.4.1 => 4.4.1 
    histoire: ^0.17.5 => 0.17.5 
    vite: ^4.5.0 => 4.5.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by peterbud** [comment]
Are you aiming to change the location of the `histoire.config.ts`? Instead of changing the `base`,  you might consider the recently added ability to specify path for histoire config file using -c or --config? See #612

**Comment by VanishMax** [comment]
@peterbud No, I mean the support for Vite's `base` option, which is not working for now. For example, for `base: 'docs'`, Histoire's stories should open not on `localhost:3000/` but on `localhost:3000/docs`

**Comment by peterbud** [comment]
I have looked it, trying to locate the issue. It seems to me this problem occurs only if the Story has a default ('single') layout.
If you add the grid layout, then it seems working.
```
  :layout="{
      type: 'grid',
      width: 200,
    }"
```

Do you see the same?

**Comment by VanishMax** [comment]
Yes, somehow it works with the grid. Interesting behaviour

**Comment by peterbud** [comment]
OK, I think I have a solution, PR is coming
