### ISSUE TITLE
Nuxt3 Public assets bug

### ISSUE THREAD

**Issue by gyxoBka** [histoire-dev/histoire#715]
### Describe the bug

Assets are not available from /assets/. Only from /public/assets which is wrong

### Reproduction

[Stackblitz](https://stackblitz.com/edit/nuxt-starter-hzvged?file=components%2FImage.story.vue)

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (6) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
  npmPackages:
    @histoire/plugin-nuxt: ^0.17.5 => 0.17.17 
    @histoire/plugin-vue: ^0.17.5 => 0.17.17 
    histoire: ^0.17.5 => 0.17.17
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/histoire-dev/histoire/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://histoire.dev/guide/).
- [X] Check that there isn't [already an issue](https://github.com/histoire-dev/histoire/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/histoire-dev/histoire/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by vivekrpatel8** [comment]
Add following to histoire.config file:

```
export default defineConfig({
  plugins: [HstVue(), HstNuxt()],
  vite: {
    publicDir: './public',
  },
})
```
