### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by Akryum** [histoire-dev/histoire#86]

**Comment by benmccann** [comment]
We've just released a major change to SvelteKit with the goal of better supporting tools in the Vite ecosystem like Histoire, Storybook, and Vitest. Hopefully it should be pretty straightforward to get a SvelteKit example working now. See more details at https://github.com/sveltejs/kit/issues/5184

I'd be happy to answer any questions from the Svelte side to help with this

**Comment by oneezy** [comment]
Would love to see this come to life! Svelte ecosystem desperately needs a way to demo components 
@Akryum and @benmccann 

I created an issue over at @babichjacob 's `svelte-add` repo also to shine some more light on this
https://github.com/svelte-add/svelte-add/issues/221

**Comment by jerrythomas** [comment]
Are there any instructions on how svelte support can be added to histoire?

**Comment by Akryum** [comment]
Now that https://github.com/histoire-dev/histoire/issues/87 is done, I can work on adding support to more frameworks :)

**Comment by gavin-noktes** [comment]
Do we have an eta on this? I would love to help however I can. Would love to start working with Histoire on svelte projects!

**Comment by oneezy** [comment]
> Now that #87 is done, I can work on adding support for more frameworks :)

@Akryum I'm also down to help get this setup

**Comment by Akryum** [comment]
I'm currently writing the code necessary to handle multiple frameworks and bed testing it with Vue 2.7

**Comment by oneezy** [comment]
Great. let us know when you need some beta testing 😉

**Comment by Akryum** [comment]
It's coming together https://github.com/histoire-dev/histoire/commit/3357c46892466144e0d163b120ee4842822dbcb8

**Comment by Akryum** [comment]
Vue 2.7 support is pushed, meaning Histoire now fully supports multiple frameworks!
https://github.com/histoire-dev/histoire/commit/e54694ae00b178bf046661252037baf1c9b8b05a

**Comment by Akryum** [comment]
Unresolved question is the builtin tailwind plugin that generates a `Tailwind.story.vue` story with Vue syntax... :brain:

**Comment by oneezy** [comment]
@babichjacob is one of the maintainers of [svelte-add](https://github.com/svelte-add/tailwindcss) .. he might have some ideas on this

**Comment by dominikg** [comment]
@Akryum  did you check out unocss + preset-wind as a replacement for tailwind? It understands tailwinds css but doesn't require extra setup for postcss and supports vue, svelte and others out of the box.

https://github.com/unocss/unocss

**Comment by Akryum** [comment]
@dominikg I'm not sure it's related to adding Svelte support, you are free to use any CSS framework you want in your Histoire project.

**Comment by Akryum** [comment]
@oneezy The unresolved question I mentionned is about the auto-generated story for Tailwind design tokens such as [this](https://vue3.examples.histoire.dev/story/tailwind?variantId=background-color) which is using Vue 3 story syntax.
https://github.com/histoire-dev/histoire/blob/8a2e8bbad77a264a2edba6ec19af0686dba7415a/packages/histoire/src/node/builtin-plugins/tailwind-tokens.ts#L83

Potential solutions I see:
- Write a different version for every possible framework (nope)
- Have a system to use the bundled version of Vue from the main UI in the story, but we would need to pre-bundle the generated component somehow (we need to not depend on `vue` and `@vite/plugin-vue` being available in the user project)
- Be able to write the story in vanilla JS without any rendering framework?

**Comment by dominikg** [comment]
Sounded like you were looking for a way to support tailwind in multiple formats, but if it is 'just' about adding a default story if the project already has a tailwind setup that's not needed.

> - Write a different version for every possible framework (nope)

It is effort, but could be provided via separate packages and possibly by thrird parties

> Have a system to use the bundled version of Vue from the main UI in the story, but we would need to pre-bundle the generated component somehow (we need to not depend on vue and @vite/plugin-vue being available in the user project)

That would be a lot of exrta for an optional featue and the end result would be very different. Projects that otherwise do not depend on vue don't need the extra weight just for a tailwind preview

> Be able to write the story in vanilla JS without any rendering framework?

Yes, a vanilla js + html story could work

All things considered i'd see this generated tailwind story as an optional feature only suitable for some projects that use tailwind. Depending on the actual config / implementation, the generated story could as well be useless as the project doesn't work that way.

So if this thing is the only blocker for svelte support i'd vouch for disabling it and release it without a generated tailwind story.

**Comment by Akryum** [comment]
> That would be a lot of extra for an optional feature and the end result would be very different. Projects that otherwise do not depend on vue don't need the extra weight just for a tailwind preview

The dependency is already there for the main Histoire UI

**Comment by Akryum** [comment]
The tailwind plugin no longer rely on `@vitejs/plugin-vue`: https://github.com/histoire-dev/histoire/commit/39a2f353376d07b0d13ed0f92a98c59747db48a5

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/184042166-ec5fbe77-b9d3-4230-950a-0137da167c1d.png)
![image](https://user-images.githubusercontent.com/2798204/184042187-fad93505-b8fa-48e3-8167-4e4714af9059.png)

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/184045471-e1ef0797-7c47-4271-bfd3-2dd2066c46e4.png)

**Comment by Akryum** [comment]
The tailwind tokens are using the pre-bundled version of Vue that comes with the main UI, so no need to install `vue` nor `@vitejs/plugin-vue` in the svelte project (even indirectly):
![image](https://user-images.githubusercontent.com/2798204/184048370-2648c7c6-7305-4880-9344-97f15913e574.png)

**Comment by oneezy** [comment]
that's awesome @Akryum ! 

Going to give this a test run when I have some time

**Comment by oneezy** [comment]
just tried to give it a go and ran into this `ERR_MODULE_NOT_FOUND` error

> _(could be me just unfamiliar with histoire setup process..but pretty sure I did everything right)_
```
pnpm i
cd ../examples/svelte3
pnpm story:dev
```
![image](https://user-images.githubusercontent.com/7369575/184253107-6489cda3-0e01-4b15-a453-a8fe9e884609.png)

```diff
$ pnpm story:dev

> histoire-example-svelte3@0.0.1 story:dev C:\Users\oneezy\Desktop\www\7.Testing\histoire\examples\svelte3        
> histoire dev

node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\oneezy\Desktop\www\7.Testing\histoire\packages\histoire\dist\node\bin.js' imported from C:\Users\oneezy\Desktop\www\7.Testing\histoire\packages\histoire\bin.mjs
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:416:11)
    at moduleResolve (node:internal/modules/esm/resolve:932:10)
    at defaultResolve (node:internal/modules/esm/resolve:1044:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
- ELIFECYCLE  Command failed with exit code 1.

**Comment by Akryum** [comment]
You need to build the repo first, see the [contributing guide](https://github.com/histoire-dev/histoire/blob/main/CONTRIBUTING.md#local-dev-setup)

**Comment by oneezy** [comment]
Well, it's trying but `pnpm run build` is erroring out.
Probably not the right place to be discussing all this but just to follow up:

**my setup**
- Windows 11
- node `v16.13.2`
- pnpm `7.9.0`
- git bash

```diff
packages/histoire-plugin-svelte build$ rimraf dist && vite build && pnpm run build:types
│ vite v3.0.5 building for production...
│ ✓ 0 modules transformed.
│ Entry module cannot be external (src/client/index.ts).
│ error during build:
│ Error: Entry module cannot be external (src/client/index.ts).
│     at error (file:///C:/Users/oneezy/Desktop/www/7.Testing/histoire/node_modules/.pnpm/rollup@2.77.2/node_modules/rollup/dist/es/shared
│     at ModuleLoader.loadEntryModule (file:///C:/Users/oneezy/Desktop/www/7.Testing/histoire/node_modules/.pnpm/rollup@2.77.2/node_module
│     at async Promise.all (index 0)
└─ Failed in 1s
```

![image](https://user-images.githubusercontent.com/7369575/184284253-cf3b4e32-07ac-40fa-ad9c-d984858880e1.png)

**Comment by Akryum** [comment]
> Windows 11

Explains it all :sweat_smile:

**Comment by Akryum** [comment]
Should be fixed on the branch

**Comment by oneezy** [comment]
Went ahead and made a demo repo for anyone who wants to try [histoire + svelte](https://github.com/oneezy/histoire-svelte)

https://github.com/oneezy/histoire-svelte

**Note:** I forced it to only install `histoire 0.10.0` due to a bug in `0.10.1` (see #239)

**Comment by sw-yx** [comment]
made one too https://github.com/sw-yx/sveltekit-monorepo - with monorepo

**Comment by oneezy** [comment]
> made one too https://github.com/sw-yx/sveltekit-monorepo - with monorepo

yo @sw-yx ! 
I actually have a [monorepo](monorepo ) with this as an option as well. Some of it was even based off your [swyx-kit](https://github.com/sw-yx/swyxkit)

Give it a spin if you like,
https://github.com/oneezy/monorepo
