### ISSUE TITLE
Vue 2.7 support

### ISSUE THREAD

**Issue by Romainpetit** [histoire-dev/histoire#98]
Vue 2.7 has been announced with a lot of compatibility with the Vue 3 ecosystem. 
Could we hope for Histoire supporting Vue 2.7?

**Comment by Akryum** [comment]
It isn't supported just yet!

**Comment by Akryum** [comment]
Closed in https://github.com/histoire-dev/histoire/commit/e54694ae00b178bf046661252037baf1c9b8b05a
